/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * API version: 2022-05-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v2022_05_01

// CompetitiveSummaryIncludedData : The supported data types in the `getCompetitiveSummary` API.
type CompetitiveSummaryIncludedData string

// List of CompetitiveSummaryIncludedData
const (
	FEATURED_BUYING_OPTIONS_CompetitiveSummaryIncludedData CompetitiveSummaryIncludedData = "featuredBuyingOptions"
	REFERENCE_PRICES_CompetitiveSummaryIncludedData        CompetitiveSummaryIncludedData = "referencePrices"
	LOWEST_PRICED_OFFERS_CompetitiveSummaryIncludedData    CompetitiveSummaryIncludedData = "lowestPricedOffers"
)
