/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * API version: 2022-05-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v2022_05_01

// A product offer with segment information indicating where it's featured.
type SegmentedFeaturedOffer struct {
	// The list of segment information in which the offer is featured.
	FeaturedOfferSegments []FeaturedOfferSegment `json:"featuredOfferSegments"`
	// The seller identifier for the offer.
	SellerId string `json:"sellerId"`
	Condition *Condition `json:"condition"`
	// The item subcondition of the offer.
	SubCondition string `json:"subCondition,omitempty"`
	FulfillmentType *FulfillmentType `json:"fulfillmentType"`
	ListingPrice *MoneyType `json:"listingPrice"`
	// A list of shipping options associated with this offer
	ShippingOptions []ShippingOption `json:"shippingOptions,omitempty"`
	Points *Points `json:"points,omitempty"`
	PrimeDetails *PrimeDetails `json:"primeDetails,omitempty"`
}
