/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * API version: 2022-05-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v2022_05_01

// Currency type and monetary value schema to demonstrate pricing information.
type MoneyType struct {
	// The currency code in ISO 4217 format.
	CurrencyCode string `json:"currencyCode,omitempty"`
	// The monetary value.
	Amount float64 `json:"amount,omitempty"`
}
