/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * API version: 2022-05-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v2022_05_01

// The response for the individual `competitiveSummary` request in the batch operation.
type CompetitiveSummaryResponse struct {
	Status *HttpStatusLine                 `json:"status"`
	Body   *CompetitiveSummaryResponseBody `json:"body"`
}
