/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_19

// Additional information related to Amazon Pay.
type AmazonPayContext struct {
	// Store name related to transaction.
	StoreName string `json:"storeName,omitempty"`
	// Order type of the transaction.
	OrderType string `json:"orderType,omitempty"`
	// Channel details of related transaction.
	Channel string `json:"channel,omitempty"`
}
