/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_19

// Related business identifier of the transaction.
type RelatedIdentifier struct {
	// Enumerated set of related business identifier names.
	RelatedIdentifierName string `json:"relatedIdentifierName,omitempty"`
	// Corresponding value of RelatedIdentifierName
	RelatedIdentifierValue string `json:"relatedIdentifierValue,omitempty"`
}
