/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_19

// Information about the marketplace where the transaction occurred.
type MarketplaceDetails struct {
	// The identifier of the marketplace where the transaction occurred. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId,omitempty"`
	// The name of the marketplace where the transaction occurred.   Example: 'Amazon.com','Amazon.in'
	MarketplaceName string `json:"marketplaceName,omitempty"`
}
