/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_19

import (
	"time"
)

// Additional Information about the item.
type Context struct {
	ContextType string `json:"contextType"`
	// The store name associated with the transaction.
	StoreName string `json:"storeName,omitempty"`
	// Order type of the transaction.
	OrderType string `json:"orderType,omitempty"`
	// Channel details of related transaction.
	Channel string `json:"channel,omitempty"`
	// Amazon Standard Identification Number (ASIN) of the item.
	Asin string `json:"asin,omitempty"`
	// Stock keeping unit (SKU) of the item.
	Sku string `json:"sku,omitempty"`
	// Quantity of the item shipped.
	QuantityShipped int32 `json:"quantityShipped,omitempty"`
	// Fulfillment network of the item.
	FulfillmentNetwork string `json:"fulfillmentNetwork,omitempty"`
	// Type of payment made.
	PaymentType string `json:"paymentType,omitempty"`
	// Method of payment made.
	PaymentMethod string `json:"paymentMethod,omitempty"`
	// Reference number of payment made.
	PaymentReference string     `json:"paymentReference,omitempty"`
	PaymentDate      *time.Time `json:"paymentDate,omitempty"`
	// The deferral policy applied to the transaction.  **Examples:** `B2B` (invoiced orders), `DD7` (delivery date policy)
	DeferralReason string     `json:"deferralReason,omitempty"`
	MaturityDate   *time.Time `json:"maturityDate,omitempty"`
	StartTime      *time.Time `json:"startTime,omitempty"`
	EndTime        *time.Time `json:"endTime,omitempty"`
}
