/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * API version: 2021-06-30
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reports_v2021_06_30

// The response for the `getReports` operation.
type GetReportsResponse struct {
	Reports *[]Report `json:"reports"`
	// Returned when the number of results exceeds `pageSize`. To get the next page of results, call `getReports` with this token as the only parameter.
	NextToken string `json:"nextToken,omitempty"`
}
