/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * API version: 2021-06-30
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reports_v2021_06_30

// A list of error responses returned when a request is unsuccessful.
type ErrorList struct {
	// Error response returned when the request is unsuccessful.
	Errors []ModelError `json:"errors"`
}
