/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_fees_v0

// A list of error responses returned when a request is unsuccessful.
type GetMyFeesEstimatesErrorList struct {
	// A list of error responses returned when a request is unsuccessful.
	Errors []ModelError `json:"errors"`
}
