/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_fees_v0

// Price information for an item, used to estimate fees.
type PriceToEstimateFees struct {
	ListingPrice *MoneyType `json:"ListingPrice"`
	Shipping *MoneyType `json:"Shipping,omitempty"`
	Points *Points `json:"Points,omitempty"`
}
