/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_fees_v0

// A product, marketplace, and proposed price used to request estimated fees.
type FeesEstimateByIdRequest struct {
	FeesEstimateRequest *FeesEstimateRequest `json:"FeesEstimateRequest,omitempty"`
	IdType *IdType `json:"IdType"`
	// The item identifier.
	IdValue string `json:"IdValue"`
}
