/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_fees_v0

// An unexpected error occurred during this operation.
type FeesEstimateError struct {
	// An error type, identifying either the receiver or the sender as the originator of the error.
	Type_ string `json:"Type"`
	// An error code that identifies the type of error that occurred.
	Code string `json:"Code"`
	// A message that describes the error condition.
	Message string `json:"Message"`
	Detail *[]interface{} `json:"Detail"`
}
