/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2020-12-01-use-case-guide).
 *
 * API version: 2020-12-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2020_12_01

// Vendor details associated with an Amazon catalog item for the indicated Amazon marketplace.
type ItemVendorDetailsByMarketplace struct {
	// Amazon marketplace identifier.
	MarketplaceId string `json:"marketplaceId"`
	// Brand code associated with an Amazon catalog item.
	BrandCode string `json:"brandCode,omitempty"`
	// Product category associated with an Amazon catalog item.
	CategoryCode string `json:"categoryCode,omitempty"`
	// Manufacturer code associated with an Amazon catalog item.
	ManufacturerCode string `json:"manufacturerCode,omitempty"`
	// Parent vendor code of the manufacturer code.
	ManufacturerCodeParent string `json:"manufacturerCodeParent,omitempty"`
	// Product group associated with an Amazon catalog item.
	ProductGroup string `json:"productGroup,omitempty"`
	// Replenishment category associated with an Amazon catalog item.
	ReplenishmentCategory string `json:"replenishmentCategory,omitempty"`
	// Product subcategory associated with an Amazon catalog item.
	SubcategoryCode string `json:"subcategoryCode,omitempty"`
}
