/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2020-12-01-use-case-guide).
 *
 * API version: 2020-12-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2020_12_01

// An item in the Amazon catalog.
type Item struct {
	Asin string `json:"asin"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Identifiers *[]ItemIdentifiersByMarketplace `json:"identifiers,omitempty"`
	Images *[]ItemImagesByMarketplace `json:"images,omitempty"`
	ProductTypes *[]ItemProductTypeByMarketplace `json:"productTypes,omitempty"`
	SalesRanks *[]ItemSalesRanksByMarketplace `json:"salesRanks,omitempty"`
	Summaries *[]ItemSummaryByMarketplace `json:"summaries,omitempty"`
	Variations *[]ItemVariationsByMarketplace `json:"variations,omitempty"`
	VendorDetails *[]ItemVendorDetailsByMarketplace `json:"vendorDetails,omitempty"`
}
