/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2020-12-01-use-case-guide).
 *
 * API version: 2020-12-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2020_12_01

// Summary details of an Amazon catalog item for the indicated Amazon marketplace.
type ItemSummaryByMarketplace struct {
	// Amazon marketplace identifier.
	MarketplaceId string `json:"marketplaceId"`
	// Name of the brand associated with an Amazon catalog item.
	BrandName string `json:"brandName,omitempty"`
	// Identifier of the browse node associated with an Amazon catalog item.
	BrowseNode string `json:"browseNode,omitempty"`
	// Name of the color associated with an Amazon catalog item.
	ColorName string `json:"colorName,omitempty"`
	// Name, or title, associated with an Amazon catalog item.
	ItemName string `json:"itemName,omitempty"`
	// Name of the manufacturer associated with an Amazon catalog item.
	Manufacturer string `json:"manufacturer,omitempty"`
	// Model number associated with an Amazon catalog item.
	ModelNumber string `json:"modelNumber,omitempty"`
	// Name of the size associated with an Amazon catalog item.
	SizeName string `json:"sizeName,omitempty"`
	// Name of the style associated with an Amazon catalog item.
	StyleName string `json:"styleName,omitempty"`
}
