/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// Details of item quantity.
type ItemQuantity struct {
	// Amount of units shipped for a specific item at a shipment level. If the item is present only in certain cartons or pallets within the shipment, please provide this at the appropriate carton or pallet level.
	Amount int32 `json:"amount"`
	// Unit of measure for the shipped quantity.
	UnitOfMeasure string `json:"unitOfMeasure"`
	// The case size, in the event that we ordered using cases. Otherwise, 1.
	UnitSize int32 `json:"unitSize,omitempty"`
	TotalWeight *TotalWeight `json:"totalWeight,omitempty"`
}
