/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// This is used only for direct import shipment confirmations.
type Route struct {
	// The port or location involved in transporting the cargo, as specified in transportation contracts or operational plans.
	Stops []Stop `json:"stops"`
}
