/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// A list of the items in this transportation and their associated inner container details. If any of the item detail fields are common at a carton or a pallet level, provide them at the corresponding carton or pallet level.
type Containers struct {
	// The type of container.
	ContainerType string `json:"containerType"`
	// An integer that must be submitted for multi-box shipments only, where one item may come in separate packages.
	ContainerSequenceNumber string `json:"containerSequenceNumber,omitempty"`
	// A list of carton identifiers.
	ContainerIdentifiers []ContainerIdentification `json:"containerIdentifiers"`
	// The tracking number used for identifying the shipment.
	TrackingNumber string `json:"trackingNumber,omitempty"`
	Dimensions *Dimensions `json:"dimensions,omitempty"`
	Weight *Weight `json:"weight,omitempty"`
	// Number of layers per pallet.
	Tier int32 `json:"tier,omitempty"`
	// Number of cartons per layer on the pallet.
	Block int32 `json:"block,omitempty"`
	InnerContainersDetails *InnerContainersDetails `json:"innerContainersDetails,omitempty"`
	// A list of packed items.
	PackedItems []PackedItems `json:"packedItems,omitempty"`
}
