/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// A list of carton identifiers.
type ContainerIdentification struct {
	// The container identification type.
	ContainerIdentificationType string `json:"containerIdentificationType"`
	// Container identification number that adheres to the definition of the container identification type.
	ContainerIdentificationNumber string `json:"containerIdentificationNumber"`
}
