/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

import (
	"time"
)

// Transport Request pickup date
type PurchaseOrders struct {
	// Purchase order numbers involved in this shipment, list all the PO that are involved as part of this shipment.
	PurchaseOrderNumber string `json:"purchaseOrderNumber,omitempty"`
	// Purchase order numbers involved in this shipment, list all the PO that are involved as part of this shipment.
	PurchaseOrderDate time.Time `json:"purchaseOrderDate,omitempty"`
	// Date range in which shipment is expected for these purchase orders.
	ShipWindow string `json:"shipWindow,omitempty"`
	// A list of the items that are associated to the PO in this transport and their associated details.
	Items []PurchaseOrderItems `json:"items,omitempty"`
}
