/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1
import (
	"time"
)

// A list of one or more shipments with respective details.
type Shipment struct {
	// Unique Transportation ID created by Vendor (Should not be used over the last 365 days).
	VendorShipmentIdentifier string `json:"vendorShipmentIdentifier"`
	// Indicates the type of transportation request (for example, `New` or `Cancel`). Each `transactionType` has a unique set of operations and there are corresponding details to be populated for each operation.
	TransactionType string `json:"transactionType"`
	// The buyer Reference Number is a unique identifier generated by buyer for all Collect/WePay shipments when you submit a transportation request. This field is mandatory for Collect/WePay shipments.
	BuyerReferenceNumber string `json:"buyerReferenceNumber,omitempty"`
	// Date on which the transportation request was submitted.
	TransactionDate time.Time `json:"transactionDate"`
	// Indicates the current shipment status.
	CurrentShipmentStatus string `json:"currentShipmentStatus,omitempty"`
	// Date and time when the last status was updated.
	CurrentshipmentStatusDate time.Time `json:"currentshipmentStatusDate,omitempty"`
	// Indicates the list of current shipment status details and when the last update was received from carrier this is available on shipment Details response.
	ShipmentStatusDetails []ShipmentStatusDetails `json:"shipmentStatusDetails,omitempty"`
	// The date and time of the shipment request created by vendor.
	ShipmentCreateDate time.Time `json:"shipmentCreateDate,omitempty"`
	// The date and time of the departure of the shipment from the vendor's location. Vendors are requested to send ASNs within 30 minutes of departure from their warehouse/distribution center or at least 6 hours prior to the appointment time at the Buyer destination warehouse, whichever is sooner. Shipped date mentioned in the shipment confirmation should not be in the future.
	ShipmentConfirmDate time.Time `json:"shipmentConfirmDate,omitempty"`
	// The date and time of the package label created for the shipment by buyer.
	PackageLabelCreateDate time.Time `json:"packageLabelCreateDate,omitempty"`
	// Specifies if payment is Collect (WePay) or Prepaid (TheyPay). Required.
	ShipmentFreightTerm string `json:"shipmentFreightTerm,omitempty"`
	SellingParty *PartyIdentification `json:"sellingParty"`
	ShipFromParty *PartyIdentification `json:"shipFromParty"`
	ShipToParty *PartyIdentification `json:"shipToParty"`
	ShipmentMeasurements *TransportShipmentMeasurements `json:"shipmentMeasurements,omitempty"`
	CollectFreightPickupDetails *CollectFreightPickupDetails `json:"collectFreightPickupDetails,omitempty"`
	// Indicates the purchase orders involved for the transportation request. This group is an array create 1 for each PO and list their corresponding items. This information is used for deciding the route,truck allocation and storage efficiently. This is a mandatory information for Buyer performing transportation from vendor warehouse (WePay/Collect)
	PurchaseOrders []PurchaseOrders `json:"purchaseOrders,omitempty"`
	ImportDetails *ImportDetails `json:"importDetails,omitempty"`
	// A list of the items in this transportation and their associated inner container details. If any of the item detail fields are common at a carton or a pallet level, provide them at the corresponding carton or pallet level.
	Containers []Containers `json:"containers,omitempty"`
	TransportationDetails *TransportationDetails `json:"transportationDetails,omitempty"`
}
