/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// The response schema for the GetShipmentLabels operation.
type GetShipmentLabels struct {
	Payload *TransportationLabels `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
