/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_shipments_v1

// Indicates the carrier details and their contact informations
type CarrierDetails struct {
	// The field is used to represent the carrier used for performing the shipment.
	Name string `json:"name,omitempty"`
	// Code that identifies the carrier for the shipment. The Standard Carrier Alpha Code (SCAC) is a unique two to four letter code used to identify a carrier. Carrier SCAC codes are assigned and maintained by the NMFTA (National Motor Freight Association).
	Code string `json:"code,omitempty"`
	// The field is used to represent the Carrier contact number.
	Phone string `json:"phone,omitempty"`
	// The field is used to represent the carrier Email id.
	Email string `json:"email,omitempty"`
	// The field is also known as PRO number is a unique number assigned by the carrier. It is used to identify and track the shipment that goes out for delivery. This field is mandatory for US, CA, MX shipment confirmations.
	ShipmentReferenceNumber string `json:"shipmentReferenceNumber,omitempty"`
}
