/*
 * Selling Partner API for Messaging
 *
 * With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package messaging_v1

// The `GET` request schema response.
type GetSchemaResponse struct {
	Links   *GetSchemaResponseLinks `json:"_links,omitempty"`
	Payload *map[string]interface{} `json:"payload,omitempty"`
	Errors  *[]ModelError           `json:"errors,omitempty"`
}
