/*
 * Selling Partner API for Direct Fulfillment Inventory Updates
 *
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_inventory_v1

// Details of item quantity.
type ItemQuantity struct {
	// Quantity of units available for a specific item.
	Amount int32 `json:"amount,omitempty"`
	// Unit of measure for the available quantity.
	UnitOfMeasure string `json:"unitOfMeasure"`
}
