/*
 * Selling Partner API for Direct Fulfillment Inventory Updates
 *
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_inventory_v1

// Updated inventory details for an item.
type ItemDetails struct {
	// The buyer selected product identification of the item. Either buyerProductIdentifier or vendorProductIdentifier should be submitted.
	BuyerProductIdentifier string `json:"buyerProductIdentifier,omitempty"`
	// The vendor selected product identification of the item. Either buyerProductIdentifier or vendorProductIdentifier should be submitted.
	VendorProductIdentifier string `json:"vendorProductIdentifier,omitempty"`
	AvailableQuantity *ItemQuantity `json:"availableQuantity"`
	// When true, the item is permanently unavailable.
	IsObsolete bool `json:"isObsolete,omitempty"`
}
