/*
 * Selling Partner API for Direct Fulfillment Inventory Updates
 *
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_inventory_v1

// The response schema for the submitInventoryUpdate operation.
type SubmitInventoryUpdateResponse struct {
	Payload *TransactionReference `json:"payload,omitempty"`
	Errors  *[]ModelError         `json:"errors,omitempty"`
}
