/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1
import (
	"time"
)

// Promised delivery information for the item.
type ItemDeliveryPromise struct {
	// The date and time of the start of the promised delivery window in ISO 8601 format.
	StartTime time.Time `json:"startTime,omitempty"`
	// The date and time of the end of the promised delivery window in ISO 8601 format.
	EndTime time.Time `json:"endTime,omitempty"`
}
