/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Information about an item associated with the service job.
type AssociatedItem struct {
	// The Amazon Standard Identification Number (ASIN) of the item.
	Asin string `json:"asin,omitempty"`
	// The title of the item.
	Title string `json:"title,omitempty"`
	// The total number of items included in the order.
	Quantity int32 `json:"quantity,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	// The status of the item.
	ItemStatus string `json:"itemStatus,omitempty"`
	// The brand name of the item.
	BrandName string `json:"brandName,omitempty"`
	ItemDelivery *ItemDelivery `json:"itemDelivery,omitempty"`
}
