/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// `UpdateReservationRecord` entity contains the `Reservation` if there is an error/warning while performing the requested operation on it, otherwise it will contain the new `reservationId`.
type UpdateReservationRecord struct {
	Reservation *Reservation `json:"reservation,omitempty"`
	Warnings *[]Warning `json:"warnings,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
