/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Range capacity entity where each entry has a capacity type and corresponding slots.
type RangeCapacity struct {
	CapacityType *CapacityType `json:"capacityType,omitempty"`
	// Array of capacity slots in range slot format.
	Slots []RangeSlot `json:"slots,omitempty"`
}
