/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// The payload for the `getServiceJobs` operation.
type JobListing struct {
	// Total result size of the query result.
	TotalResultSize int32 `json:"totalResultSize,omitempty"`
	// A generated string used to pass information to your next request. If `nextPageToken` is returned, pass the value of `nextPageToken` to the `pageToken` to get next results.
	NextPageToken string `json:"nextPageToken,omitempty"`
	// A generated string used to pass information to your next request. If `previousPageToken` is returned, pass the value of `previousPageToken` to the `pageToken` to get previous page results.
	PreviousPageToken string `json:"previousPageToken,omitempty"`
	// List of job details for the given input.
	Jobs []ServiceJob `json:"jobs,omitempty"`
}
