/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Input for set appointment fulfillment data operation.
type SetAppointmentFulfillmentDataRequest struct {
	EstimatedArrivalTime *DateTimeRange         `json:"estimatedArrivalTime,omitempty"`
	FulfillmentTime      *FulfillmentTime       `json:"fulfillmentTime,omitempty"`
	AppointmentResources *[]AppointmentResource `json:"appointmentResources,omitempty"`
	FulfillmentDocuments *[]FulfillmentDocument `json:"fulfillmentDocuments,omitempty"`
}
