/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

import (
	"time"
)

// The time of the appointment window.
type AppointmentTime struct {
	// The date and time of the start of the appointment window in ISO 8601 format.
	StartTime time.Time `json:"startTime"`
	// The duration of the appointment window, in minutes.
	DurationInMinutes int32 `json:"durationInMinutes"`
}
