/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

import (
	"time"
)

// Input for fulfillment time details
type FulfillmentTime struct {
	// The date, time in UTC of the fulfillment start time in ISO 8601 format.
	StartTime time.Time `json:"startTime,omitempty"`
	// The date, time in UTC of the fulfillment end time in ISO 8601 format.
	EndTime time.Time `json:"endTime,omitempty"`
}
