/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Document that captured during service appointment fulfillment that portrays proof of completion
type FulfillmentDocument struct {
	// The identifier of the upload destination. Get this value by calling the `createServiceDocumentUploadDestination` operation of the Services API.
	UploadDestinationId string `json:"uploadDestinationId,omitempty"`
	// Sha256 hash of the file content. This value is used to determine if the file has been corrupted or tampered with during transit.
	ContentSha256 string `json:"contentSha256,omitempty"`
}
