/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Information about the buyer.
type Buyer struct {
	// The identifier of the buyer.
	BuyerId string `json:"buyerId,omitempty"`
	// The name of the buyer.
	Name string `json:"name,omitempty"`
	// The phone number of the buyer.
	Phone string `json:"phone,omitempty"`
	// When true, the service is for an Amazon Prime buyer.
	IsPrimeMember bool `json:"isPrimeMember,omitempty"`
}
