/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Input for to be uploaded document.
type ServiceUploadDocument struct {
	// The content type of the to-be-uploaded file
	ContentType string `json:"contentType"`
	// The content length of the to-be-uploaded file
	ContentLength float64 `json:"contentLength"`
	// An MD5 hash of the content to be submitted to the upload destination. This value is used to determine if the data has been corrupted or tampered with during transit.
	ContentMD5 string `json:"contentMD5,omitempty"`
}
