/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1
// DayOfWeek : The day of the week.
type DayOfWeek string

// List of DayOfWeek
const (
	MONDAY_DayOfWeek DayOfWeek = "MONDAY"
	TUESDAY_DayOfWeek DayOfWeek = "TUESDAY"
	WEDNESDAY_DayOfWeek DayOfWeek = "WEDNESDAY"
	THURSDAY_DayOfWeek DayOfWeek = "THURSDAY"
	FRIDAY_DayOfWeek DayOfWeek = "FRIDAY"
	SATURDAY_DayOfWeek DayOfWeek = "SATURDAY"
	SUNDAY_DayOfWeek DayOfWeek = "SUNDAY"
)
