/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// The response of fetching appointment slots based on service context.
type GetAppointmentSlotsResponse struct {
	Payload *AppointmentSlotReport `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
