/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Response schema for the `addAppointmentForServiceJobByServiceJobId` and `rescheduleAppointmentForServiceJobByServiceJobId` operations.
type SetAppointmentResponse struct {
	AppointmentId string `json:"appointmentId,omitempty"`
	Warnings *[]Warning `json:"warnings,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
