/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

// Response schema for the `getFixedSlotCapacity` operation.
type FixedSlotCapacity struct {
	// Resource Identifier.
	ResourceId string `json:"resourceId,omitempty"`
	// The duration of each slot which is returned. This value will be a multiple of 5 and fall in the following range: 5 <= `slotDuration` <= 360.
	SlotDuration float64 `json:"slotDuration,omitempty"`
	// Array of capacity slots in fixed slot format.
	Capacities []FixedSlot `json:"capacities,omitempty"`
	// Next page token, if there are more pages.
	NextPageToken string `json:"nextPageToken,omitempty"`
}
