/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package services_v1

import (
	"time"
)

// In this slot format each slot only has the requested capacity types. This slot size is as specified by slot duration.
type FixedSlot struct {
	// Start date time of slot in ISO 8601 format with precision of seconds.
	StartDateTime time.Time `json:"startDateTime,omitempty"`
	// Scheduled capacity corresponding to the slot. This capacity represents the originally allocated capacity as per resource schedule.
	ScheduledCapacity int32 `json:"scheduledCapacity,omitempty"`
	// Available capacity corresponding to the slot. This capacity represents the capacity available for allocation to reservations.
	AvailableCapacity int32 `json:"availableCapacity,omitempty"`
	// Encumbered capacity corresponding to the slot. This capacity represents the capacity allocated for Amazon Jobs/Appointments/Orders.
	EncumberedCapacity int32 `json:"encumberedCapacity,omitempty"`
	// Reserved capacity corresponding to the slot. This capacity represents the capacity made unavailable due to events like Breaks/Leaves/Lunch.
	ReservedCapacity int32 `json:"reservedCapacity,omitempty"`
}
