/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_orders_v1

// Tax registration details of the entity.
type TaxRegistrationDetails struct {
	// Tax registration type for the entity.
	TaxRegistrationType string `json:"taxRegistrationType"`
	// Tax registration number for the entity. For example, VAT ID.
	TaxRegistrationNumber string `json:"taxRegistrationNumber"`
}
