/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_orders_v1

// A list of orders returned as response.
type OrderList struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	// Represents an individual order within the OrderList.
	Orders []Order `json:"orders,omitempty"`
}
