/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_orders_v1

// The response schema for the submitAcknowledgement operation
type SubmitAcknowledgementResponse struct {
	Payload *TransactionId `json:"payload,omitempty"`
	Errors  *[]ModelError  `json:"errors,omitempty"`
}
