/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_orders_v1
import (
	"time"
)

// Item receive status at the buyer's warehouse.
type OrderItemStatusReceivingStatus struct {
	// Receive status of the line item.
	ReceiveStatus string `json:"receiveStatus,omitempty"`
	ReceivedQuantity *ItemQuantity `json:"receivedQuantity,omitempty"`
	// The date when the most recent item was received at the buyer's warehouse. Must be in ISO-8601 date/time format.
	LastReceiveDate time.Time `json:"lastReceiveDate,omitempty"`
}
