/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * API version: 2021-06-30
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package feeds_v2021_06_30

import (
	"time"
)

// Detailed information about the feed.
type Feed struct {
	// The identifier for the feed. This identifier is unique only in combination with a seller ID.
	FeedId string `json:"feedId"`
	// The feed type.
	FeedType string `json:"feedType"`
	// A list of identifiers for the marketplaces that the feed is applied to.
	MarketplaceIds []string `json:"marketplaceIds,omitempty"`
	// The date and time when the feed was created, in ISO 8601 date time format.
	CreatedTime time.Time `json:"createdTime"`
	// The processing status of the feed.
	ProcessingStatus string `json:"processingStatus"`
	// The date and time when feed processing started, in ISO 8601 date time format.
	ProcessingStartTime time.Time `json:"processingStartTime,omitempty"`
	// The date and time when feed processing completed, in ISO 8601 date time format.
	ProcessingEndTime time.Time `json:"processingEndTime,omitempty"`
	// The identifier for the feed document. This identifier is unique only in combination with a seller ID.
	ResultFeedDocumentId string `json:"resultFeedDocumentId,omitempty"`
}
