/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * API version: 2021-06-30
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package feeds_v2021_06_30

// Specifies the content type for the createFeedDocument operation.
type CreateFeedDocumentSpecification struct {
	// The content type of the feed.
	ContentType string `json:"contentType"`
}
