/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// Dimensions of the package.
type PackageDimensions struct {
	// Height of the package.
	Height float64 `json:"height"`
	// Length of the package.
	Length            float64                     `json:"length"`
	UnitOfMeasurement *DimensionUnitOfMeasurement `json:"unitOfMeasurement"`
	// Width of the package.
	Width float64 `json:"width"`
}
