/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// Represents the contents inside a package, which can be products or a nested package.
type DistributionPackageContents struct {
	// This is required only when `DistributionPackageType=PALLET`.
	Packages []DistributionPackageQuantity `json:"packages,omitempty"`
	// This is required only when `DistributionPackageType=CASE`.
	Products []ProductQuantity `json:"products,omitempty"`
}
