/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// Represents the ineligibility reason for one SKU.
type SkuIneligibilityReason struct {
	// Code for the SKU ineligibility.
	Code string `json:"code"`
	// Detailed description of the SKU ineligibility.
	Description string `json:"description"`
}
