/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// LabelOwner : The entity that labels the products.
type LabelOwner string

// List of LabelOwner
const (
	AMAZON_LabelOwner LabelOwner = "AMAZON"
	SELF_LabelOwner   LabelOwner = "SELF"
)
