/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// Payload for creating an inbound order.
type InboundOrderCreationData struct {
	// Reference ID that can be used to correlate the order with partner resources.
	ExternalReferenceId string   `json:"externalReferenceId,omitempty"`
	OriginAddress       *Address `json:"originAddress"`
	// List of packages to be inbounded.
	PackagesToInbound []DistributionPackageQuantity `json:"packagesToInbound"`
	Preferences       *InboundPreferences           `json:"preferences,omitempty"`
}
