/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

import (
	"time"
)

// Represents a product with the SKU details and the corresponding quantity.
type ProductQuantity struct {
	// Contains attributes for this instance of the product. For example, item color, or other attributes that distinguish the product beyond the SKU. This is metadata for the product and Amazon does not process this data.
	Attributes []ProductAttribute `json:"attributes,omitempty"`
	// Product quantity.
	Quantity int32 `json:"quantity"`
	// The seller or merchant SKU.
	Sku string `json:"sku"`
	// The expiration date for the SKU. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
	Expiration  time.Time    `json:"expiration,omitempty"`
	PrepDetails *PrepDetails `json:"prepDetails,omitempty"`
}
