/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * API version: 2024-05-09
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazon_warehousing_and_distribution_model_v2024_05_09

// Error response returned when the request is unsuccessful.
type ModelError struct {
	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`
	// Additional details that can help the caller understand or fix the issue.
	Details string `json:"details,omitempty"`
	// A message that describes the error condition.
	Message string `json:"message"`
}
