/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v1

// Details of quantity ordered.
type ItemQuantity struct {
	// Acknowledged quantity. This value should not be zero.
	Amount int32 `json:"amount,omitempty"`
	// Unit of measure for the acknowledged quantity.
	UnitOfMeasure string `json:"unitOfMeasure,omitempty"`
}
