/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v1

// Name, address and tax details of a party.
type PartyIdentification struct {
	// Assigned identification for the party. For example, warehouse code or vendor code. Please refer to specific party for more details.
	PartyId string `json:"partyId"`
	Address *Address `json:"address,omitempty"`
	TaxInfo *TaxRegistrationDetails `json:"taxInfo,omitempty"`
}
