/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v1

// An amount of money, including units in the form of currency.
type Money struct {
	// Three digit currency code in ISO 4217 format. String of length 3.
	CurrencyCode string `json:"currencyCode,omitempty"`
	Amount string `json:"amount,omitempty"`
}
