/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v1
import (
	"time"
)

// Details of an order.
type OrderDetails struct {
	// The customer order number.
	CustomerOrderNumber string `json:"customerOrderNumber"`
	// The date the order was placed. This field is expected to be in ISO-8601 date/time format, for example:2018-07-16T23:00:00Z/ 2018-07-16T23:00:00-05:00 /2018-07-16T23:00:00-08:00. If no time zone is specified, UTC should be assumed.
	OrderDate time.Time `json:"orderDate"`
	// Current status of the order.
	OrderStatus string `json:"orderStatus,omitempty"`
	ShipmentDetails *ShipmentDetails `json:"shipmentDetails"`
	TaxTotal *OrderDetailsTaxTotal `json:"taxTotal,omitempty"`
	SellingParty *PartyIdentification `json:"sellingParty"`
	ShipFromParty *PartyIdentification `json:"shipFromParty"`
	ShipToParty *Address `json:"shipToParty"`
	BillToParty *PartyIdentification `json:"billToParty"`
	// A list of items in this purchase order.
	Items []OrderItem `json:"items"`
}
