/*
 * The Selling Partner API for Automotive.
 *
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * API version: 2024-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vehicles_v2024_11_01

// When a request produces a response that exceeds the `pageSize`, pagination occurs. This means the response is divided into individual pages. To retrieve the next page or the previous page, you must pass the `nextToken` value or the `previousToken` value as the `pageToken` parameter in the next request. When you receive the last page, there will be no `nextToken` key in the pagination object.
type Pagination struct {
	// A token that can be used to fetch the next page.
	NextToken string `json:"nextToken,omitempty"`
	// A token that can be used to fetch the previous page.
	PreviousToken string `json:"previousToken,omitempty"`
}
