/*
 * The Selling Partner API for Automotive.
 *
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * API version: 2024-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vehicles_v2024_11_01

// Combinations of attributes and unique identifier that represents a vehicle in vehicle list.
type Vehicle struct {
	// Vehicle Brand.
	Make string `json:"make"`
	// Specific model of a vehicle.
	Model string `json:"model"`
	// Name of the vehicle variant.
	VariantName string `json:"variantName,omitempty"`
	// Body style of vehicle (example: Hatchback, Cabriolet).
	BodyStyle string `json:"bodyStyle,omitempty"`
	// Drive type of vehicle(example: Rear wheel drive).
	DriveType string `json:"driveType,omitempty"`
	// Energy Source for the vehicle(example: Petrol)
	Energy string `json:"energy,omitempty"`
	// Engine output of vehicle.
	EngineOutput []EngineOutput `json:"engineOutput,omitempty"`
	ManufacturingStartDate *MonthAndYear `json:"manufacturingStartDate,omitempty"`
	ManufacturingStopDate *MonthAndYear `json:"manufacturingStopDate,omitempty"`
	// The date on which the vehicle was last updated, in ISO-8601 date/time format.
	LastProcessedDate string `json:"lastProcessedDate,omitempty"`
	Status *VehicleStatusInCatalog `json:"status,omitempty"`
	// Identifiers that can be used to identify the vehicle uniquely
	Identifiers []VehicleIdentifiers `json:"identifiers"`
}
