/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fba_inventory_v1

// An item to be created in the inventory.
type CreateInventoryItemRequest struct {
	// The seller SKU of the item.
	SellerSku string `json:"sellerSku"`
	// The marketplaceId.
	MarketplaceId string `json:"marketplaceId"`
	// The name of the item.
	ProductName string `json:"productName"`
}
