/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fba_inventory_v1

// An item in the list of inventory to be added.
type InventoryItem struct {
	// The seller SKU of the item.
	SellerSku string `json:"sellerSku"`
	// The marketplaceId.
	MarketplaceId string `json:"marketplaceId"`
	// The quantity of item to add.
	Quantity int32 `json:"quantity"`
}
