/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fba_inventory_v1

// The object with the list of Inventory to be added
type AddInventoryRequest struct {
	InventoryItems *[]InventoryItem `json:"inventoryItems,omitempty"`
}
