/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0

// An item of a shipment, refund, guarantee claim, or chargeback.
type ShipmentItem struct {
	// The seller SKU of the item. The seller SKU is qualified by the seller's seller ID, which is included with every call to the Selling Partner API.
	SellerSKU string `json:"SellerSKU,omitempty"`
	// An Amazon-defined order item identifier.
	OrderItemId string `json:"OrderItemId,omitempty"`
	// An Amazon-defined order adjustment identifier defined for refunds, guarantee claims, and chargeback events.
	OrderAdjustmentItemId string `json:"OrderAdjustmentItemId,omitempty"`
	// The number of items shipped.
	QuantityShipped          int32                   `json:"QuantityShipped,omitempty"`
	ItemChargeList           *[]ChargeComponent      `json:"ItemChargeList,omitempty"`
	ItemChargeAdjustmentList *[]ChargeComponent      `json:"ItemChargeAdjustmentList,omitempty"`
	ItemFeeList              *[]FeeComponent         `json:"ItemFeeList,omitempty"`
	ItemFeeAdjustmentList    *[]FeeComponent         `json:"ItemFeeAdjustmentList,omitempty"`
	ItemTaxWithheldList      *[]TaxWithheldComponent `json:"ItemTaxWithheldList,omitempty"`
	PromotionList            *[]Promotion            `json:"PromotionList,omitempty"`
	PromotionAdjustmentList  *[]Promotion            `json:"PromotionAdjustmentList,omitempty"`
	CostOfPointsGranted      *Currency               `json:"CostOfPointsGranted,omitempty"`
	CostOfPointsReturned     *Currency               `json:"CostOfPointsReturned,omitempty"`
}
