/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0

import (
	"time"
)

// A credit given to a solution provider.
type SolutionProviderCreditEvent struct {
	// The transaction type.
	ProviderTransactionType string `json:"ProviderTransactionType,omitempty"`
	// A seller-defined identifier for an order.
	SellerOrderId string `json:"SellerOrderId,omitempty"`
	// The identifier of the marketplace where the order was placed.
	MarketplaceId string `json:"MarketplaceId,omitempty"`
	// The two-letter country code of the country associated with the marketplace where the order was placed.
	MarketplaceCountryCode string `json:"MarketplaceCountryCode,omitempty"`
	// The Amazon-defined identifier of the seller.
	SellerId string `json:"SellerId,omitempty"`
	// The store name where the payment event occurred.
	SellerStoreName string `json:"SellerStoreName,omitempty"`
	// The Amazon-defined identifier of the solution provider.
	ProviderId string `json:"ProviderId,omitempty"`
	// The store name where the payment event occurred.
	ProviderStoreName       string     `json:"ProviderStoreName,omitempty"`
	TransactionAmount       *Currency  `json:"TransactionAmount,omitempty"`
	TransactionCreationDate *time.Time `json:"TransactionCreationDate,omitempty"`
}
