/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0
import (
	"time"
)

// An event related to coupon payments.
type CouponPaymentEvent struct {
	PostedDate *time.Time `json:"PostedDate,omitempty"`
	// A coupon identifier.
	CouponId string `json:"CouponId,omitempty"`
	// The description provided by the seller when they created the coupon.
	SellerCouponDescription string `json:"SellerCouponDescription,omitempty"`
	// The number of coupon clips or redemptions.
	ClipOrRedemptionCount int64 `json:"ClipOrRedemptionCount,omitempty"`
	// A payment event identifier.
	PaymentEventId string `json:"PaymentEventId,omitempty"`
	FeeComponent *FeeComponent `json:"FeeComponent,omitempty"`
	ChargeComponent *ChargeComponent `json:"ChargeComponent,omitempty"`
	TotalAmount *Currency `json:"TotalAmount,omitempty"`
}
