/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0

import (
	"time"
)

// An expense related to an affordability promotion.
type AffordabilityExpenseEvent struct {
	// An Amazon-defined identifier for an order.
	AmazonOrderId string     `json:"AmazonOrderId,omitempty"`
	PostedDate    *time.Time `json:"PostedDate,omitempty"`
	// An encrypted, Amazon-defined marketplace identifier.
	MarketplaceId string `json:"MarketplaceId,omitempty"`
	// Indicates the type of transaction.   Possible values:  * Charge - For an affordability promotion expense.  * Refund - For an affordability promotion expense reversal.
	TransactionType string    `json:"TransactionType,omitempty"`
	BaseExpense     *Currency `json:"BaseExpense,omitempty"`
	TaxTypeCGST     *Currency `json:"TaxTypeCGST"`
	TaxTypeSGST     *Currency `json:"TaxTypeSGST"`
	TaxTypeIGST     *Currency `json:"TaxTypeIGST"`
	TotalExpense    *Currency `json:"TotalExpense,omitempty"`
}
