/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0
import (
	"time"
)

// An event related to a rental transaction.
type RentalTransactionEvent struct {
	// An Amazon-defined identifier for an order.
	AmazonOrderId string `json:"AmazonOrderId,omitempty"`
	// The type of rental event.  Possible values:  * RentalCustomerPayment-Buyout - Transaction type that represents when the customer wants to buy out a rented item.  * RentalCustomerPayment-Extension - Transaction type that represents when the customer wants to extend the rental period.  * RentalCustomerRefund-Buyout - Transaction type that represents when the customer requests a refund for the buyout of the rented item.  * RentalCustomerRefund-Extension - Transaction type that represents when the customer requests a refund over the extension on the rented item.  * RentalHandlingFee - Transaction type that represents the fee that Amazon charges sellers who rent through Amazon.  * RentalChargeFailureReimbursement - Transaction type that represents when Amazon sends money to the seller to compensate for a failed charge.  * RentalLostItemReimbursement - Transaction type that represents when Amazon sends money to the seller to compensate for a lost item.
	RentalEventType string `json:"RentalEventType,omitempty"`
	// The number of days that the buyer extended an already rented item. This value is only returned for RentalCustomerPayment-Extension and RentalCustomerRefund-Extension events.
	ExtensionLength int32 `json:"ExtensionLength,omitempty"`
	PostedDate *time.Time `json:"PostedDate,omitempty"`
	RentalChargeList *[]ChargeComponent `json:"RentalChargeList,omitempty"`
	RentalFeeList *[]FeeComponent `json:"RentalFeeList,omitempty"`
	// The name of the marketplace.
	MarketplaceName string `json:"MarketplaceName,omitempty"`
	RentalInitialValue *Currency `json:"RentalInitialValue,omitempty"`
	RentalReimbursement *Currency `json:"RentalReimbursement,omitempty"`
	RentalTaxWithheldList *[]TaxWithheldComponent `json:"RentalTaxWithheldList,omitempty"`
}
