/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0
import (
	"time"
)

// An event linked to the payment of a fee related to the specified deal.
type SellerDealPaymentEvent struct {
	PostedDate *time.Time `json:"postedDate,omitempty"`
	// The unique identifier of the deal.
	DealId string `json:"dealId,omitempty"`
	// The internal description of the deal.
	DealDescription string `json:"dealDescription,omitempty"`
	// The type of event: SellerDealComplete.
	EventType string `json:"eventType,omitempty"`
	// The type of fee: RunLightningDealFee.
	FeeType string `json:"feeType,omitempty"`
	FeeAmount *Currency `json:"feeAmount,omitempty"`
	TaxAmount *Currency `json:"taxAmount,omitempty"`
	TotalAmount *Currency `json:"totalAmount,omitempty"`
}
