/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0

import (
	"time"
)

// An event related to an Adhoc Disbursement.
type AdhocDisbursementEvent struct {
	// Indicates the type of transaction.  Example: \"Disbursed to Amazon Gift Card balance\"
	TransactionType string     `json:"TransactionType,omitempty"`
	PostedDate      *time.Time `json:"PostedDate,omitempty"`
	// The identifier for the transaction.
	TransactionId     string    `json:"TransactionId,omitempty"`
	TransactionAmount *Currency `json:"TransactionAmount,omitempty"`
}
