/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0
import (
	"time"
)

// An event related to a trial shipment.
type TrialShipmentEvent struct {
	// An Amazon-defined identifier for an order.
	AmazonOrderId string `json:"AmazonOrderId,omitempty"`
	// The identifier of the financial event group.
	FinancialEventGroupId string `json:"FinancialEventGroupId,omitempty"`
	PostedDate *time.Time `json:"PostedDate,omitempty"`
	// The seller SKU of the item. The seller SKU is qualified by the seller's seller ID, which is included with every call to the Selling Partner API.
	SKU string `json:"SKU,omitempty"`
	FeeList *[]FeeComponent `json:"FeeList,omitempty"`
}
