/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0
import (
	"time"
)

// A Sponsored Products payment event.
type ProductAdsPaymentEvent struct {
	PostedDate *time.Time `json:"postedDate,omitempty"`
	// Indicates if the transaction is for a charge or a refund.  Possible values:  * charge - Charge  * refund - Refund
	TransactionType string `json:"transactionType,omitempty"`
	// Identifier for the invoice that the transaction appears in.
	InvoiceId string `json:"invoiceId,omitempty"`
	BaseValue *Currency `json:"baseValue,omitempty"`
	TaxValue *Currency `json:"taxValue,omitempty"`
	TransactionValue *Currency `json:"transactionValue,omitempty"`
}
