/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v0

import (
	"time"
)

// A payment event for Fulfillment by Amazon (FBA) inventory liquidation. This event is used only in the US marketplace.
type FbaLiquidationEvent struct {
	PostedDate *time.Time `json:"PostedDate,omitempty"`
	// The identifier for the original removal order.
	OriginalRemovalOrderId    string    `json:"OriginalRemovalOrderId,omitempty"`
	LiquidationProceedsAmount *Currency `json:"LiquidationProceedsAmount,omitempty"`
	LiquidationFeeAmount      *Currency `json:"LiquidationFeeAmount,omitempty"`
}
