/*
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * API version: 2022-03-23
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package easy_ship_model_v2022_03_23

// The request schema for the `updateScheduledPackages` operation.
type UpdateScheduledPackagesRequest struct {
	MarketplaceId            string                  `json:"marketplaceId"`
	UpdatePackageDetailsList *[]UpdatePackageDetails `json:"updatePackageDetailsList"`
}
