/*
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * API version: 2022-03-23
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package easy_ship_model_v2022_03_23

// The response schema for the bulk scheduling API. It returns by the bulk scheduling API containing an array of the scheduled packtages, an optional list of orders we couldn't schedule with the reason, and a pre-signed URL for a ZIP file containing the associated shipping labels plus the documents enabled for your marketplace.
type CreateScheduledPackagesResponse struct {
	// A list of packages. Refer to the `Package` object.
	ScheduledPackages []ModelPackage `json:"scheduledPackages,omitempty"`
	// A list of orders we couldn't scheduled on your behalf. Each element contains the reason and details on the error.
	RejectedOrders []RejectedOrder `json:"rejectedOrders,omitempty"`
	PrintableDocumentsUrl string `json:"printableDocumentsUrl,omitempty"`
}
