/*
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * API version: 2022-03-23
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package easy_ship_model_v2022_03_23
// UnitOfWeight : The unit of measurement used to measure the weight.
type UnitOfWeight string

// List of UnitOfWeight
const (
	GRAMS_UnitOfWeight UnitOfWeight = "Grams"
	G_UnitOfWeight UnitOfWeight = "G"
)
