/*
 * Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data
 *
 * The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.
 *
 * API version: 2021-10-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_sandbox_test_data_v2021_10_28

// The request body for the generateOrderScenarios operation.
type GenerateOrderScenarioRequest struct {
	// The list of test orders requested as indicated by party identifiers.
	Orders []OrderScenarioRequest `json:"orders,omitempty"`
}
