/*
 * Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data
 *
 * The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.
 *
 * API version: 2021-10-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_sandbox_test_data_v2021_10_28

// The transaction details including the status. If the transaction was successful, also includes the requested test order data.
type Transaction struct {
	// The unique identifier returned in the response to the generateOrderScenarios request.
	TransactionId string `json:"transactionId"`
	// The current processing status of the transaction.
	Status string `json:"status"`
	TestCaseData *TestCaseData `json:"testCaseData,omitempty"`
}
