/*
 * Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data
 *
 * The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.
 *
 * API version: 2021-10-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_sandbox_test_data_v2021_10_28

// A list of error responses returned when a request is unsuccessful.
type ErrorList struct {
	// An array of individual error objects containing error details.
	Errors []ModelError `json:"errors"`
}
