/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders_v0

// A single order item.
type OrderItem struct {
	// The item's Amazon Standard Identification Number (ASIN).
	ASIN string `json:"ASIN"`
	// The item's seller stock keeping unit (SKU).
	SellerSKU string `json:"SellerSKU,omitempty"`
	// An Amazon-defined order item identifier.
	OrderItemId string `json:"OrderItemId"`
	// A list of associated items that a customer has purchased with a product. For example, a tire installation service purchased with tires.
	AssociatedItems []AssociatedItem `json:"AssociatedItems,omitempty"`
	// The item's name.
	Title string `json:"Title,omitempty"`
	// The number of items in the order.
	QuantityOrdered int32 `json:"QuantityOrdered"`
	// The number of items shipped.
	QuantityShipped      int32                `json:"QuantityShipped,omitempty"`
	ProductInfo          *ProductInfoDetail   `json:"ProductInfo,omitempty"`
	PointsGranted        *PointsGrantedDetail `json:"PointsGranted,omitempty"`
	ItemPrice            *Money               `json:"ItemPrice,omitempty"`
	ShippingPrice        *Money               `json:"ShippingPrice,omitempty"`
	ItemTax              *Money               `json:"ItemTax,omitempty"`
	ShippingTax          *Money               `json:"ShippingTax,omitempty"`
	ShippingDiscount     *Money               `json:"ShippingDiscount,omitempty"`
	ShippingDiscountTax  *Money               `json:"ShippingDiscountTax,omitempty"`
	PromotionDiscount    *Money               `json:"PromotionDiscount,omitempty"`
	PromotionDiscountTax *Money               `json:"PromotionDiscountTax,omitempty"`
	PromotionIds         *[]string            `json:"PromotionIds,omitempty"`
	CODFee               *Money               `json:"CODFee,omitempty"`
	CODFeeDiscount       *Money               `json:"CODFeeDiscount,omitempty"`
	// Indicates whether the item is a gift.  **Possible values**: `true` and `false`.
	IsGift string `json:"IsGift,omitempty"`
	// The condition of the item, as described by the seller.
	ConditionNote string `json:"ConditionNote,omitempty"`
	// The condition of the item.  **Possible values**: `New`, `Used`, `Collectible`, `Refurbished`, `Preorder`, and `Club`.
	ConditionId string `json:"ConditionId,omitempty"`
	// The subcondition of the item.  **Possible values**: `New`, `Mint`, `Very Good`, `Good`, `Acceptable`, `Poor`, `Club`, `OEM`, `Warranty`, `Refurbished Warranty`, `Refurbished`, `Open Box`, `Any`, and `Other`.
	ConditionSubtypeId string `json:"ConditionSubtypeId,omitempty"`
	// The start date of the scheduled delivery window in the time zone for the order destination. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format.
	ScheduledDeliveryStartDate string `json:"ScheduledDeliveryStartDate,omitempty"`
	// The end date of the scheduled delivery window in the time zone for the order destination. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format.
	ScheduledDeliveryEndDate string `json:"ScheduledDeliveryEndDate,omitempty"`
	// Indicates that the selling price is a special price that is only available for Amazon Business orders. For more information about the Amazon Business Seller Program, refer to the [Amazon Business website](https://www.amazon.com/b2b/info/amazon-business).   **Possible values**: `BusinessPrice`
	PriceDesignation string         `json:"PriceDesignation,omitempty"`
	TaxCollection    *TaxCollection `json:"TaxCollection,omitempty"`
	// When true, the product type for this item has a serial number.   Only returned for Amazon Easy Ship orders.
	SerialNumberRequired bool `json:"SerialNumberRequired,omitempty"`
	// When true, the ASIN is enrolled in Transparency. The Transparency serial number that you must submit is determined by:  **1D or 2D Barcode:** This has a **T** logo. Submit either the 29-character alpha-numeric identifier beginning with **AZ** or **ZA**, or the 38-character Serialized Global Trade Item Number (SGTIN). **2D Barcode SN:** Submit the 7- to 20-character serial number barcode, which likely has the prefix **SN**. The serial number is applied to the same side of the packaging as the GTIN (UPC/EAN/ISBN) barcode. **QR code SN:** Submit the URL that the QR code generates.
	IsTransparency bool `json:"IsTransparency,omitempty"`
	// The IOSS number of the marketplace. Sellers shipping to the EU from outside the EU must provide this IOSS number to their carrier when Amazon has collected the VAT on the sale.
	IossNumber string `json:"IossNumber,omitempty"`
	// The store chain store identifier. Linked to a specific store in a store chain.
	StoreChainStoreId string `json:"StoreChainStoreId,omitempty"`
	// The category of deemed reseller. This applies to selling partners that are not based in the EU and is used to help them meet the VAT Deemed Reseller tax laws in the EU and UK.
	DeemedResellerCategory string                `json:"DeemedResellerCategory,omitempty"`
	BuyerInfo              *ItemBuyerInfo        `json:"BuyerInfo,omitempty"`
	BuyerRequestedCancel   *BuyerRequestedCancel `json:"BuyerRequestedCancel,omitempty"`
	// A list of serial numbers for electronic products that are shipped to customers. Returned for FBA orders only.
	SerialNumbers           []string                 `json:"SerialNumbers,omitempty"`
	SubstitutionPreferences *SubstitutionPreferences `json:"SubstitutionPreferences,omitempty"`
	Measurement             *Measurement             `json:"Measurement,omitempty"`
	ShippingConstraints     *ShippingConstraints     `json:"ShippingConstraints,omitempty"`
	AmazonPrograms          *AmazonPrograms          `json:"AmazonPrograms,omitempty"`
}
