/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders_v0

// Contains the business invoice tax information. Available only in the TR marketplace.
type BuyerTaxInformation struct {
	// Business buyer's company legal name.
	BuyerLegalCompanyName string `json:"BuyerLegalCompanyName,omitempty"`
	// Business buyer's address.
	BuyerBusinessAddress string `json:"BuyerBusinessAddress,omitempty"`
	// Business buyer's tax registration ID.
	BuyerTaxRegistrationId string `json:"BuyerTaxRegistrationId,omitempty"`
	// Business buyer's tax office.
	BuyerTaxOffice string `json:"BuyerTaxOffice,omitempty"`
}
