/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders_v0

// The shipping address for the order.
type OrderAddress struct {
	// An Amazon-defined order identifier, in 3-7-7 format.
	AmazonOrderId string `json:"AmazonOrderId"`
	// The company name of the contact buyer. For IBA orders, the buyer company must be Amazon entities.
	BuyerCompanyName    string               `json:"BuyerCompanyName,omitempty"`
	ShippingAddress     *Address             `json:"ShippingAddress,omitempty"`
	DeliveryPreferences *DeliveryPreferences `json:"DeliveryPreferences,omitempty"`
}
