/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders_v0

// Buyer information for an order.
type OrderBuyerInfo struct {
	// An Amazon-defined order identifier, in 3-7-7 format.
	AmazonOrderId string `json:"AmazonOrderId"`
	// The anonymized email address of the buyer.
	BuyerEmail string `json:"BuyerEmail,omitempty"`
	// The buyer name or the recipient name.
	BuyerName string `json:"BuyerName,omitempty"`
	// The county of the buyer.  **Note**: This attribute is only available in the Brazil marketplace.
	BuyerCounty  string        `json:"BuyerCounty,omitempty"`
	BuyerTaxInfo *BuyerTaxInfo `json:"BuyerTaxInfo,omitempty"`
	// The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout.
	PurchaseOrderNumber string `json:"PurchaseOrderNumber,omitempty"`
}
