/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// Role of an individual contributor in the creation of an item, such as author or actor.
type ItemContributorRole struct {
	// Display name of the role in the requested locale, such as `Author` or `Actor`.
	DisplayName string `json:"displayName,omitempty"`
	// Role value for the Amazon catalog item, such as `author` or `actor`.
	Value string `json:"value"`
}
