/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// A brand that you can use to refine your search.
type BrandRefinement struct {
	// The estimated number of results that would be returned if you refine your search by the specified `brandName`.
	NumberOfResults int32 `json:"numberOfResults"`
	// The brand name that you can use to refine your search.
	BrandName string `json:"brandName"`
}
