/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// Information about an Amazon catalog item for the indicated `marketplaceId`.
type ItemSummaryByMarketplace struct {
	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
	// When `true`, the Amazon catalog item is intended for an adult audience or is sexual in nature.
	AdultProduct bool `json:"adultProduct,omitempty"`
	// When `true`, the Amazon catalog item is autographed.
	Autographed bool `json:"autographed,omitempty"`
	// Name of the brand that is associated with the Amazon catalog item.
	Brand string `json:"brand,omitempty"`
	BrowseClassification *ItemBrowseClassification `json:"browseClassification,omitempty"`
	// The color that is associated with the Amazon catalog item.
	Color string `json:"color,omitempty"`
	// Individual contributors to the creation of the item, such as the authors or actors.
	Contributors []ItemContributor `json:"contributors,omitempty"`
	// Classification type that is associated with the Amazon catalog item.
	ItemClassification string `json:"itemClassification,omitempty"`
	// The name that is associated with the Amazon catalog item.
	ItemName string `json:"itemName,omitempty"`
	// The name of the manufacturer that is associated with the Amazon catalog item.
	Manufacturer string `json:"manufacturer,omitempty"`
	// When true, the item is classified as memorabilia.
	Memorabilia bool `json:"memorabilia,omitempty"`
	// The model number that is associated with the Amazon catalog item.
	ModelNumber string `json:"modelNumber,omitempty"`
	// The quantity of the Amazon catalog item within one package.
	PackageQuantity int32 `json:"packageQuantity,omitempty"`
	// The part number that is associated with the Amazon catalog item.
	PartNumber string `json:"partNumber,omitempty"`
	// The earliest date on which the Amazon catalog item can be shipped to customers.
	ReleaseDate string `json:"releaseDate,omitempty"`
	// The name of the size of the Amazon catalog item.
	Size string `json:"size,omitempty"`
	// The name of the style that is associated with the Amazon catalog item.
	Style string `json:"style,omitempty"`
	// When true, the Amazon catalog item is eligible for trade-in.
	TradeInEligible bool `json:"tradeInEligible,omitempty"`
	// The identifier of the website display group that is associated with the Amazon catalog item.
	WebsiteDisplayGroup string `json:"websiteDisplayGroup,omitempty"`
	// The display name of the website display group that is associated with the Amazon catalog item.
	WebsiteDisplayGroupName string `json:"websiteDisplayGroupName,omitempty"`
}
