/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// Sales ranks of an Amazon catalog item, grouped by `marketplaceId`.
type ItemSalesRanksByMarketplace struct {
	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
	// Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by classification.
	ClassificationRanks []ItemClassificationSalesRank `json:"classificationRanks,omitempty"`
	// Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by website display group.
	DisplayGroupRanks []ItemDisplayGroupSalesRank `json:"displayGroupRanks,omitempty"`
}
