/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// Image for an item in the Amazon catalog.
type ItemImage struct {
	// Variant of the image, such as `MAIN` or `PT01`.
	Variant string `json:"variant"`
	// URL for the image.
	Link string `json:"link"`
	// Height of the image in pixels.
	Height int32 `json:"height"`
	// Width of the image in pixels.
	Width int32 `json:"width"`
}
