/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// Relationship details for an Amazon catalog item.
type ItemRelationship struct {
	// ASINs of the related items that are children of this item.
	ChildAsins []string `json:"childAsins,omitempty"`
	// ASINs of the related items that are parents of this item.
	ParentAsins []string `json:"parentAsins,omitempty"`
	VariationTheme *ItemVariationTheme `json:"variationTheme,omitempty"`
	// Type of relationship.
	Type_ string `json:"type"`
}
