/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v2022_04_01

// The vendor details that are associated with an Amazon catalog item for the specified `marketplaceId`.
type ItemVendorDetailsByMarketplace struct {
	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
	// The brand code that is associated with an Amazon catalog item.
	BrandCode string `json:"brandCode,omitempty"`
	// The manufacturer code that is associated with an Amazon catalog item.
	ManufacturerCode string `json:"manufacturerCode,omitempty"`
	// The parent vendor code of the manufacturer code.
	ManufacturerCodeParent string `json:"manufacturerCodeParent,omitempty"`
	ProductCategory *ItemVendorDetailsCategory `json:"productCategory,omitempty"`
	// The product group that is associated with an Amazon catalog item.
	ProductGroup string `json:"productGroup,omitempty"`
	ProductSubcategory *ItemVendorDetailsCategory `json:"productSubcategory,omitempty"`
	// The replenishment category that is associated with an Amazon catalog item.
	ReplenishmentCategory string `json:"replenishmentCategory,omitempty"`
}
