/*
 * Selling Partner API for Retail Procurement Transaction Status
 *
 * The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_transaction_status_v1

// The transaction status.
type Transaction struct {
	// The unique identifier returned in the 'transactionId' field in response to the post request of a specific transaction.
	TransactionId string `json:"transactionId"`
	// Current processing status of the transaction.
	Status string        `json:"status"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
