/*
 * Selling Partner API for Direct Fulfillment Transaction Status
 *
 * The Selling Partner API for Direct Fulfillment Transaction Status provides programmatic access to a direct fulfillment vendor's transaction status.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_transactions_v2021_12_28

// The payload for the getTransactionStatus operation.
type TransactionStatus struct {
	TransactionStatus *Transaction `json:"transactionStatus,omitempty"`
}
