/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// Represents the request payload for submitting updates to the status of shipments, containing an array of one or more ShipmentStatusUpdate objects.
type SubmitShipmentStatusUpdatesRequest struct {
	// Contains a list of one or more ShipmentStatusUpdate objects, each representing an update to the status of a specific shipment.
	ShipmentStatusUpdates []ShipmentStatusUpdate `json:"shipmentStatusUpdates,omitempty"`
}
