/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// The request schema for the submitShippingLabelRequest operation.
type SubmitShippingLabelsRequest struct {
	// An array of shipping label requests to be processed.
	ShippingLabelRequests []ShippingLabelRequest `json:"shippingLabelRequests,omitempty"`
}
