/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

import (
	"time"
)

// Details for the shipment status update given by the vendor for the specific package.
type StatusUpdateDetails struct {
	// This is required to be provided for every package and should match with the trackingNumber sent for the shipment confirmation.
	TrackingNumber string `json:"trackingNumber"`
	// Indicates the shipment status code of the package that provides transportation information for Amazon tracking systems and ultimately for the final customer. For more information, refer to the [Additional Fields Explanation](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-shipping-api-use-case-guide#additional-fields-explanation).
	StatusCode string `json:"statusCode"`
	// Provides a reason code for the status of the package that will provide additional information about the transportation status. For more information, refer to the [Additional Fields Explanation](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-shipping-api-use-case-guide#additional-fields-explanation).
	ReasonCode string `json:"reasonCode"`
	// The date and time when the shipment status was updated. This field is expected to be in ISO-8601 date/time format, with UTC time zone or UTC offset. For example, 2020-07-16T23:00:00Z or 2020-07-16T23:00:00+01:00.
	StatusDateTime        time.Time                            `json:"statusDateTime"`
	StatusLocationAddress *Address                             `json:"statusLocationAddress"`
	ShipmentSchedule      *StatusUpdateDetailsShipmentSchedule `json:"shipmentSchedule,omitempty"`
}
