/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// The response schema for the getCustomerInvoices operation.
type GetCustomerInvoicesResponse struct {
	Payload *CustomerInvoiceList `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
