/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

import (
	"time"
)

// Details about a shipment.
type ShipmentDetails struct {
	// This field indicates the date of the departure of the shipment from vendor's location. Vendors are requested to send ASNs within 30 minutes of departure from their warehouse/distribution center or at least 6 hours prior to the appointment time at the Amazon destination warehouse, whichever is sooner. Shipped date mentioned in the Shipment Confirmation should not be in the future.
	ShippedDate time.Time `json:"shippedDate"`
	// Indicate the shipment status.
	ShipmentStatus string `json:"shipmentStatus"`
	// Provide the priority of the shipment.
	IsPriorityShipment bool `json:"isPriorityShipment,omitempty"`
	// The vendor order number is a unique identifier generated by a vendor for their reference.
	VendorOrderNumber string `json:"vendorOrderNumber,omitempty"`
	// Date on which the shipment is expected to reach the buyer's warehouse. It needs to be an estimate based on the average transit time between the ship-from location and the destination. The exact appointment time will be provided by buyer and is potentially not known when creating the shipment confirmation.
	EstimatedDeliveryDate time.Time `json:"estimatedDeliveryDate,omitempty"`
}
