/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// Represents a customer invoice associated with a purchase order.
type CustomerInvoice struct {
	// The purchase order number for this order.
	PurchaseOrderNumber string `json:"purchaseOrderNumber"`
	// The Base64encoded customer invoice.
	Content string `json:"content"`
}
