/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// Packing slip information.
type PackingSlip struct {
	// Purchase order number of the shipment that corresponds to the packing slip.
	PurchaseOrderNumber string `json:"purchaseOrderNumber"`
	// A Base64encoded string of the packing slip PDF.
	Content string `json:"content"`
	// The format of the file such as PDF, JPEG etc.
	ContentType string `json:"contentType,omitempty"`
}
