/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// A list of packing slips.
type PackingSlipList struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	// An array of packing slip objects.
	PackingSlips []PackingSlip `json:"packingSlips,omitempty"`
}
