/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v1

// Tax registration details of the entity.
type TaxRegistrationDetails struct {
	// Tax registration type for the entity.
	TaxRegistrationType string `json:"taxRegistrationType,omitempty"`
	// Tax registration number for the party. For example, VAT ID.
	TaxRegistrationNumber  string   `json:"taxRegistrationNumber"`
	TaxRegistrationAddress *Address `json:"taxRegistrationAddress,omitempty"`
	// Tax registration message that can be used for additional tax related details.
	TaxRegistrationMessages string `json:"taxRegistrationMessages,omitempty"`
}
