/*
 * Selling Partner API for Sales
 *
 * The Selling Partner API for Sales provides APIs related to sales performance.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sales_v1

// The response schema for the getOrderMetrics operation.
type GetOrderMetricsResponse struct {
	Payload *[]OrderMetricsInterval `json:"payload,omitempty"`
	Errors  *[]ModelError           `json:"errors,omitempty"`
}
