/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19
import (
	"time"
)

// Provides detailed information about an invoice.
type Invoice struct {
	// The date and time the invoice is issued. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
	Date time.Time `json:"date,omitempty"`
	// If the invoice is in an error state, this attribute displays the error code.
	ErrorCode string `json:"errorCode,omitempty"`
	// The invoice identifier that is used by an external party. This is typically the government agency that authorized the invoice.
	ExternalInvoiceId string `json:"externalInvoiceId,omitempty"`
	// The response message from the government authority when there is an error during invoice issuance.
	GovResponse string `json:"govResponse,omitempty"`
	// The invoice identifier.
	Id string `json:"id,omitempty"`
	// The classification of the invoice type. This varies across marketplaces. Use the `getInvoicesAttributes` operation to check `invoiceType` options.
	InvoiceType string `json:"invoiceType,omitempty"`
	// Use this identifier in conjunction with `externalInvoiceId` to identify invoices from the same seller.
	Series string `json:"series,omitempty"`
	// The invoice status classification. Use the `getInvoicesAttributes` operation to check invoice status options.
	Status string `json:"status,omitempty"`
	// List with identifiers for the transactions associated to the invoice.
	TransactionIds []TransactionIdentifier `json:"transactionIds,omitempty"`
	// Classification of the transaction that originated this invoice. Use the `getInvoicesAttributes` operation to check `transactionType` options.
	TransactionType string `json:"transactionType,omitempty"`
}
