/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19

// An object that contains the invoice attributes definition.
type InvoicesAttributes struct {
	// A list of all the options that are available for the invoice status attribute.
	InvoiceStatusOptions []AttributeOption `json:"invoiceStatusOptions,omitempty"`
	// A list of all the options that are available for the invoice type attribute.
	InvoiceTypeOptions []AttributeOption `json:"invoiceTypeOptions,omitempty"`
	// A list of all the options that are available for the transaction identifier name attribute.
	TransactionIdentifierNameOptions []AttributeOption `json:"transactionIdentifierNameOptions,omitempty"`
	// A list of all the options that are available for the transaction type attribute.
	TransactionTypeOptions []AttributeOption `json:"transactionTypeOptions,omitempty"`
}
