/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19
import (
	"time"
)

// Detailed information about the export.
type Export struct {
	// When the export generation fails, this attribute contains a description of the error.
	ErrorMessage string `json:"errorMessage,omitempty"`
	// The export identifier.
	ExportId string `json:"exportId,omitempty"`
	// The date and time when the export generation finished. Vales are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
	GenerateExportFinishedAt time.Time `json:"generateExportFinishedAt,omitempty"`
	// The date and time when the export generation started. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
	GenerateExportStartedAt time.Time `json:"generateExportStartedAt,omitempty"`
	// The identifier for the export documents. To get the information required to retrieve the export document's contents, pass each ID in the `getInvoicesDocument` operation.  This list is empty until the status is `DONE`.
	InvoicesDocumentIds []string `json:"invoicesDocumentIds,omitempty"`
	Status *ExportStatus `json:"status,omitempty"`
}
