/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19
// ExportStatus : The current status of the request.
type ExportStatus string

// List of ExportStatus
const (
	REQUESTED_ExportStatus ExportStatus = "REQUESTED"
	PROCESSING_ExportStatus ExportStatus = "PROCESSING"
	DONE_ExportStatus ExportStatus = "DONE"
	ERROR__ExportStatus ExportStatus = "ERROR"
)
