/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19

// An object that contains the `documentId` and an S3 pre-signed URL that you can use to download the specified file.
type InvoicesDocument struct {
	// The identifier of the export document.
	InvoicesDocumentId string `json:"invoicesDocumentId,omitempty"`
	// A pre-signed URL that you can use to download the invoices document in zip format. This URL expires after 30 seconds.
	InvoicesDocumentUrl string `json:"invoicesDocumentUrl,omitempty"`
}
