/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * API version: 2024-06-19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package invoices_v2024_06_19

// The error response that is returned when the request is unsuccessful.
type ModelError struct {
	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`
	// Additional details that can help the caller understand or fix the issue.
	Details string `json:"details,omitempty"`
	// A message that describes the error condition.
	Message string `json:"message"`
}
