/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_invoices_v1

// The aggregate weight of this item being invoiced. This information will be available for items sold by weight.
type TotalWeight struct {
	// The unit of measure for items sold by weight.
	UnitOfMeasure string `json:"unitOfMeasure"`
	Amount string `json:"amount"`
}
