/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_invoices_v1

// Additional information provided by the selling party for tax-related or any other purpose.
type AdditionalDetails struct {
	// The type of the additional information provided by the selling party.
	Type_ string `json:"type"`
	// The detail of the additional information provided by the selling party.
	Detail string `json:"detail"`
	// The language code of the additional information detail.
	LanguageCode string `json:"languageCode,omitempty"`
}
