/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_invoices_v1

// Details of quantity.
type ItemQuantity struct {
	// Quantity of an item. This value should not be zero.
	Amount int32 `json:"amount"`
	// Unit of measure for the quantity.
	UnitOfMeasure string `json:"unitOfMeasure"`
	// The case size, if the unit of measure value is Cases.
	UnitSize    int32        `json:"unitSize,omitempty"`
	TotalWeight *TotalWeight `json:"totalWeight,omitempty"`
}
