/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_invoices_v1

// NetCostUnitOfMeasure : This field represents weight unit of measure of items that are ordered by cases and supporting priced by weight.
type NetCostUnitOfMeasure string

// List of NetCostUnitOfMeasure
const (
	POUNDS_NetCostUnitOfMeasure    NetCostUnitOfMeasure = "POUNDS"
	OUNCES_NetCostUnitOfMeasure    NetCostUnitOfMeasure = "OUNCES"
	GRAMS_NetCostUnitOfMeasure     NetCostUnitOfMeasure = "GRAMS"
	KILOGRAMS_NetCostUnitOfMeasure NetCostUnitOfMeasure = "KILOGRAMS"
)
