/*
 * Selling Partner API for Retail Procurement Payments
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_invoices_v1

// Tax registration details of the entity.
type TaxRegistrationDetails struct {
	// The tax registration type for the entity.
	TaxRegistrationType string `json:"taxRegistrationType"`
	// The tax registration number for the entity. For example, VAT ID, Consumption Tax ID.
	TaxRegistrationNumber string `json:"taxRegistrationNumber"`
}
