/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * API version: 2021-08-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package listings_items_v2021_08_01

// The relationship details for a listing item.
type ItemRelationship struct {
	// Identifiers (SKUs) of the related items that are children of this listing item.
	ChildSkus []string `json:"childSkus,omitempty"`
	// Identifiers (SKUs) of the related items that are parents of this listing item.
	ParentSkus []string `json:"parentSkus,omitempty"`
	VariationTheme *ItemVariationTheme `json:"variationTheme,omitempty"`
	// The type of relationship.
	Type_ string `json:"type"`
}
