/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// The document specifications requested. For calls to the purchaseShipment operation, the shipment purchase fails if the specified document specifications are not among those returned in the response to the getRates operation.
type RequestedDocumentSpecification struct {
	Format          *DocumentFormat `json:"format"`
	Size            *DocumentSize   `json:"size"`
	Dpi             int32           `json:"dpi,omitempty"`
	PageLayout      string          `json:"pageLayout,omitempty"`
	NeedFileJoining bool            `json:"needFileJoining"`
	// A list of the document types requested.
	RequestedDocumentTypes      []DocumentType               `json:"requestedDocumentTypes"`
	RequestedLabelCustomization *RequestedLabelCustomization `json:"requestedLabelCustomization,omitempty"`
}
