/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// The monetary value in the currency indicated, in ISO 4217 standard format.
type Currency struct {
	// The monetary value.
	Value float64 `json:"value"`
	// The ISO 4217 format 3-character currency code.
	Unit string `json:"unit"`
}
