/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// LabelAttribute : Enumerates the attributes supported to be printed on a shipping label. The values for these attributes are retrieved from GetRates/OneClickShipment request
type LabelAttribute string

// List of LabelAttribute
const (
	PACKAGE_CLIENT_REFERENCE_ID_LabelAttribute LabelAttribute = "PACKAGE_CLIENT_REFERENCE_ID"
	SELLER_DISPLAY_NAME_LabelAttribute         LabelAttribute = "SELLER_DISPLAY_NAME"
	COLLECT_ON_DELIVERY_AMOUNT_LabelAttribute  LabelAttribute = "COLLECT_ON_DELIVERY_AMOUNT"
)
