/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Contains detail codes that provide additional details related to the forward and return leg of the shipment.
type TrackingDetailCodes struct {
	// Contains detail codes that provide additional details related to the forward leg of the shipment.
	Forward []DetailCodes `json:"forward"`
	// Contains detail codes that provide additional details related to the return leg of the shipment.
	Returns []DetailCodes `json:"returns"`
}
