/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// The format options available for a label.
type PrintOption struct {
	// A list of the supported DPI options for a document.
	SupportedDPIs []int32 `json:"supportedDPIs,omitempty"`
	// A list of the supported page layout options for a document.
	SupportedPageLayouts []string `json:"supportedPageLayouts"`
	// A list of the supported needFileJoining boolean values for a document.
	SupportedFileJoiningOptions []bool `json:"supportedFileJoiningOptions"`
	// A list of the supported documented details.
	SupportedDocumentDetails []SupportedDocumentDetail `json:"supportedDocumentDetails"`
}
