/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Active Account Details
type CollectionFormsHistoryRecord struct {
	CarrierName string `json:"carrierName,omitempty"`
	// Creation Time for this account.
	CreationDate string `json:"creationDate,omitempty"`
	GenerationStatus *GenerationStatus `json:"generationStatus,omitempty"`
	CollectionFormId string `json:"collectionFormId,omitempty"`
	ShipFromAddress *Address `json:"shipFromAddress,omitempty"`
}
