/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Detailed information for an ineligible shipping service offering.
type IneligibleRate struct {
	ServiceId   string `json:"serviceId"`
	ServiceName string `json:"serviceName"`
	CarrierName string `json:"carrierName"`
	CarrierId   string `json:"carrierId"`
	// A list of reasons why a shipping service offering is ineligible.
	IneligibilityReasons []IneligibilityReason `json:"ineligibilityReasons"`
}
