/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

import (
	"time"
)

// The request schema for the OneClickShipment operation. When the channelType is not Amazon, shipTo is required and when channelType is Amazon shipTo is ignored.
type OneClickShipmentRequest struct {
	ShipTo   *Address `json:"shipTo,omitempty"`
	ShipFrom *Address `json:"shipFrom"`
	ReturnTo *Address `json:"returnTo,omitempty"`
	// The ship date and time (the requested pickup). This defaults to the current date and time.
	ShipDate                      time.Time                            `json:"shipDate,omitempty"`
	GoodsOwner                    *GoodsOwner                          `json:"goodsOwner,omitempty"`
	Packages                      *[]ModelPackage                      `json:"packages"`
	ValueAddedServicesDetails     *[]OneClickShipmentValueAddedService `json:"valueAddedServicesDetails,omitempty"`
	TaxDetails                    *[]TaxDetail                         `json:"taxDetails,omitempty"`
	ChannelDetails                *ChannelDetails                      `json:"channelDetails"`
	LabelSpecifications           *RequestedDocumentSpecification      `json:"labelSpecifications"`
	ServiceSelection              *ServiceSelection                    `json:"serviceSelection"`
	ShipperInstruction            *ShipperInstruction                  `json:"shipperInstruction,omitempty"`
	DestinationAccessPointDetails *AccessPointDetails                  `json:"destinationAccessPointDetails,omitempty"`
}
