/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Defines the latitude and longitude of the access point.
type Geocode struct {
	// The latitude of access point.
	Latitude string `json:"latitude,omitempty"`
	// The longitude of access point.
	Longitude string `json:"longitude,omitempty"`
}
