/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

import (
	"time"
)

// The invoice details for charges associated with the goods in the package. Only applies to certain regions.
type InvoiceDetails struct {
	// The invoice number of the item.
	InvoiceNumber string `json:"invoiceNumber,omitempty"`
	// The invoice date of the item in ISO 8061 format.
	InvoiceDate time.Time `json:"invoiceDate,omitempty"`
}
