/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// ValidationMetadata Details
type ValidationMetadata struct {
	// errorMessage for the error.
	ErrorMessage string `json:"errorMessage,omitempty"`
	// validationStrategy for the error.
	ValidationStrategy string `json:"validationStrategy,omitempty"`
	// Value.
	Value string `json:"value,omitempty"`
}
