/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2
import (
	"time"
)

// The start and end time that specifies the time interval of an event.
type TimeWindow struct {
	// The start time of the time window.
	Start time.Time `json:"start,omitempty"`
	// The end time of the time window.
	End time.Time `json:"end,omitempty"`
}
