/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// The request schema for the purchaseShipment operation.
type PurchaseShipmentRequest struct {
	RequestToken                   string                          `json:"requestToken"`
	RateId                         string                          `json:"rateId"`
	RequestedDocumentSpecification *RequestedDocumentSpecification `json:"requestedDocumentSpecification"`
	RequestedValueAddedServices    *[]RequestedValueAddedService   `json:"requestedValueAddedServices,omitempty"`
	// The additional inputs required to purchase a shipping offering, in JSON format. The JSON provided here must adhere to the JSON schema that is returned in the response to the getAdditionalInputs operation.  Additional inputs are only required when indicated by the requiresAdditionalInputs property in the response to the getRates operation.
	AdditionalInputs map[string]interface{} `json:"additionalInputs,omitempty"`
}
