/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Document specification that is supported for a service offering.
type SupportedDocumentSpecification struct {
	Format       *DocumentFormat `json:"format"`
	Size         *DocumentSize   `json:"size"`
	PrintOptions *[]PrintOption  `json:"printOptions"`
}
