/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Defines the accessibility details of the access point.
type AccessibilityAttributes struct {
	// The approximate distance of access point from input postalCode's centroid.
	Distance string `json:"distance,omitempty"`
	// The approximate (static) drive time from input postal code's centroid.
	DriveTime int32 `json:"driveTime,omitempty"`
}
