/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

import (
	"time"
)

// A tracking event.
type Event struct {
	EventCode *EventCode `json:"eventCode"`
	Location  *Location  `json:"location,omitempty"`
	// The ISO 8601 formatted timestamp of the event.
	EventTime    time.Time     `json:"eventTime"`
	ShipmentType *ShipmentType `json:"shipmentType,omitempty"`
}
