/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2
import (
	"time"
)

// Additional information required for the NDR action that has been filed. If the NDR Action is RESCHEDULE, rescheduleDate is a required field. Otherwise, if the NDR Action is REATTEMPT, additionalAddressNotes is a required field. 
type NdrRequestData struct {
	// The date on which the Seller wants to reschedule shipment delivery, in ISO-8601 date/time format
	RescheduleDate time.Time `json:"rescheduleDate,omitempty"`
	AdditionalAddressNotes string `json:"additionalAddressNotes,omitempty"`
}
