/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// DetailCodes : A list of codes used to provide additional shipment information.
type DetailCodes string

// List of DetailCodes
const (
	BUSINESS_CLOSED_DetailCodes                         DetailCodes = "BusinessClosed"
	CUSTOMER_UNAVAILABLE_DetailCodes                    DetailCodes = "CustomerUnavailable"
	PAYMENT_NOT_READY_DetailCodes                       DetailCodes = "PaymentNotReady"
	OTP_NOT_AVAILABLE_DetailCodes                       DetailCodes = "OtpNotAvailable"
	DELIVERY_ATTEMPTED_DetailCodes                      DetailCodes = "DeliveryAttempted"
	UNABLE_TO_ACCESS_DetailCodes                        DetailCodes = "UnableToAccess"
	UNABLE_TO_CONTACT_RECIPIENT_DetailCodes             DetailCodes = "UnableToContactRecipient"
	DELIVERED_TO_BEHIND_WHEELIE_BIN_DetailCodes         DetailCodes = "DeliveredToBehindWheelieBin"
	DELIVERED_TO_PORCH_DetailCodes                      DetailCodes = "DeliveredToPorch"
	DELIVERED_TO_GARAGE_DetailCodes                     DetailCodes = "DeliveredToGarage"
	DELIVERED_TO_GARDEN_DetailCodes                     DetailCodes = "DeliveredToGarden"
	DELIVERED_TO_GREENHOUSE_DetailCodes                 DetailCodes = "DeliveredToGreenhouse"
	DELIVERED_TO_MAIL_SLOT_DetailCodes                  DetailCodes = "DeliveredToMailSlot"
	DELIVERED_TO_MAIL_ROOM_DetailCodes                  DetailCodes = "DeliveredToMailRoom"
	DELIVERED_TO_NEIGHBOR_DetailCodes                   DetailCodes = "DeliveredToNeighbor"
	DELIVERED_TO_REAR_DOOR_DetailCodes                  DetailCodes = "DeliveredToRearDoor"
	DELIVERED_TO_RECEPTIONIST_DetailCodes               DetailCodes = "DeliveredToReceptionist"
	DELIVERED_TO_SHED_DetailCodes                       DetailCodes = "DeliveredToShed"
	DELIVERED_WITH_OTP_DetailCodes                      DetailCodes = "DeliveredWithOTP"
	SIGNED_DetailCodes                                  DetailCodes = "Signed"
	DAMAGED_DetailCodes                                 DetailCodes = "Damaged"
	INCORRECT_ITEMS_DetailCodes                         DetailCodes = "IncorrectItems"
	NOT_REQUIRED_DetailCodes                            DetailCodes = "NotRequired"
	REJECTED_DetailCodes                                DetailCodes = "Rejected"
	REJECTED_BY_RECIPIENT_WITH_VERIFICATION_DetailCodes DetailCodes = "RejectedByRecipientWithVerification"
	CANCELLED_BY_RECIPIENT_DetailCodes                  DetailCodes = "CancelledByRecipient"
	ADDRESS_NOT_FOUND_DetailCodes                       DetailCodes = "AddressNotFound"
	HAZMAT_SHIPMENT_DetailCodes                         DetailCodes = "HazmatShipment"
	UNDELIVERABLE_DetailCodes                           DetailCodes = "Undeliverable"
	ARRIVED_AT_LOCAL_FACILITY_DetailCodes               DetailCodes = "ArrivedAtLocalFacility"
)
