/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// RateItemType : Type of the rateItem.
type RateItemType string

// List of RateItemType
const (
	MANDATORY_RateItemType RateItemType = "MANDATORY"
	OPTIONAL_RateItemType  RateItemType = "OPTIONAL"
	INCLUDED_RateItemType  RateItemType = "INCLUDED"
)
