/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// Info About CarrierAccountInput
type CarrierAccountInput struct {
	// descriptionLocalizationKey value .
	DescriptionLocalizationKey string `json:"descriptionLocalizationKey,omitempty"`
	// name value .
	Name string `json:"name,omitempty"`
	// groupName value .
	GroupName string `json:"groupName,omitempty"`
	InputType *InputType `json:"inputType,omitempty"`
	// mandatory or not  value .
	IsMandatory bool `json:"isMandatory,omitempty"`
	// is value is Confidential .
	IsConfidential bool `json:"isConfidential,omitempty"`
	// is value is hidden .
	IsHidden bool `json:"isHidden,omitempty"`
	ValidationMetadata *[]ValidationMetadata `json:"validationMetadata,omitempty"`
}
