/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// The request schema for the directPurchaseShipment operation. When the channel type is Amazon, the shipTo address is not required and will be ignored.
type DirectPurchaseRequest struct {
	ShipTo *Address `json:"shipTo,omitempty"`
	ShipFrom *Address `json:"shipFrom,omitempty"`
	ReturnTo *Address `json:"returnTo,omitempty"`
	Packages *[]ModelPackage `json:"packages,omitempty"`
	ChannelDetails *ChannelDetails `json:"channelDetails"`
	LabelSpecifications *RequestedDocumentSpecification `json:"labelSpecifications,omitempty"`
}
