/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// EventCode : The tracking event type.
type EventCode string

// List of EventCode
const (
	READY_FOR_RECEIVE_EventCode                             EventCode = "ReadyForReceive"
	PICKUP_DONE_EventCode                                   EventCode = "PickupDone"
	DELIVERED_EventCode                                     EventCode = "Delivered"
	DEPARTED_EventCode                                      EventCode = "Departed"
	DELIVERY_ATTEMPTED_EventCode                            EventCode = "DeliveryAttempted"
	LOST_EventCode                                          EventCode = "Lost"
	OUT_FOR_DELIVERY_EventCode                              EventCode = "OutForDelivery"
	ARRIVED_AT_CARRIER_FACILITY_EventCode                   EventCode = "ArrivedAtCarrierFacility"
	REJECTED_EventCode                                      EventCode = "Rejected"
	UNDELIVERABLE_EventCode                                 EventCode = "Undeliverable"
	PICKUP_CANCELLED_EventCode                              EventCode = "PickupCancelled"
	RETURN_INITIATED_EventCode                              EventCode = "ReturnInitiated"
	AVAILABLE_FOR_PICKUP_EventCode                          EventCode = "AvailableForPickup"
	RECIPIENT_REQUESTED_ALTERNATE_DELIVERY_TIMING_EventCode EventCode = "RecipientRequestedAlternateDeliveryTiming"
)
