/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * API version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipping_v2

// DocumentFormat : The file format of the document.
type DocumentFormat string

// List of DocumentFormat
const (
	PDF_DocumentFormat DocumentFormat = "PDF"
	PNG_DocumentFormat DocumentFormat = "PNG"
	ZPL_DocumentFormat DocumentFormat = "ZPL"
)
