/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * API version: 2023-11-15
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package data_kiosk_v2023_11_15

// When a query produces results that are not included in the data document, pagination occurs. This means the results are divided into pages. To retrieve the next page, you must pass a `CreateQuerySpecification` object with `paginationToken` set to this object's `nextToken` and with `query` set to this object's `query` in the subsequent `createQuery` request. When there are no more pages to fetch, the `nextToken` field will be absent.
type QueryPagination struct {
	// A token that can be used to fetch the next page of results.
	NextToken string `json:"nextToken,omitempty"`
}
