/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * API version: 2023-11-15
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package data_kiosk_v2023_11_15

// The response for the `getDocument` operation.
type GetDocumentResponse struct {
	// The identifier for the Data Kiosk document. This identifier is unique only in combination with a selling partner account ID.
	DocumentId string `json:"documentId"`
	// A presigned URL that can be used to retrieve the Data Kiosk document. This URL expires after 5 minutes. If the Data Kiosk document is compressed, the `Content-Encoding` header will indicate the compression algorithm.  **Note:** Most HTTP clients are capable of automatically decompressing downloaded files based on the `Content-Encoding` header.
	DocumentUrl string `json:"documentUrl"`
}
