/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * API version: 2023-11-15
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package data_kiosk_v2023_11_15

import (
	"time"
)

// Detailed information about the query.
type Query struct {
	// The query identifier. This identifier is unique only in combination with a selling partner account ID.
	QueryId string `json:"queryId"`
	// The submitted query.
	Query string `json:"query"`
	// The date and time when the query was created, in ISO 8601 date time format.
	CreatedTime time.Time `json:"createdTime"`
	// The processing status of the query.
	ProcessingStatus string `json:"processingStatus"`
	// The date and time when the query processing started, in ISO 8601 date time format.
	ProcessingStartTime time.Time `json:"processingStartTime,omitempty"`
	// The date and time when the query processing completed, in ISO 8601 date time format.
	ProcessingEndTime time.Time `json:"processingEndTime,omitempty"`
	// The data document identifier. This identifier is only present when there is data available as a result of the query. This identifier is unique only in combination with a selling partner account ID. Pass this identifier into the `getDocument` operation to get the information required to retrieve the data document's contents.
	DataDocumentId string `json:"dataDocumentId,omitempty"`
	// The error document identifier. This identifier is only present when an error occurs during query processing. This identifier is unique only in combination with a selling partner account ID. Pass this identifier into the `getDocument` operation to get the information required to retrieve the error document's contents.
	ErrorDocumentId string           `json:"errorDocumentId,omitempty"`
	Pagination      *QueryPagination `json:"pagination,omitempty"`
}
