/*
 * Selling Partner API for Notifications
 *
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, refer to the [Notifications Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide).
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package notifications_v1

// Information about the destination created when you call the `createDestination` operation.
type Destination struct {
	// The developer-defined name for this destination.
	Name string `json:"name"`
	// The destination identifier generated when you created the destination.
	DestinationId string               `json:"destinationId"`
	Resource      *DestinationResource `json:"resource"`
}
