/*
 * The Selling Partner API for third party application integrations.
 *
 * With the AppIntegrations API v2024-04-01, you can send notifications to Amazon Selling Partners and display the notifications in Seller Central.
 *
 * API version: 2024-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package application_integrations_v2024_04_01

// The response for the `createNotification` operation.
type CreateNotificationResponse struct {
	// The unique identifier assigned to each notification.
	NotificationId string `json:"notificationId,omitempty"`
}
