/*
 * Selling Partner API for Product Type Definitions
 *
 * The Selling Partner API for Product Type Definitions provides programmatic access to attribute and data requirements for product types in the Amazon catalog. Use this API to return the JSON Schema for a product type that you can then use with other Selling Partner APIs, such as the Selling Partner API for Listings Items, the Selling Partner API for Catalog Items, and the Selling Partner API for Feeds (for JSON-based listing feeds).  For more information, see the [Product Type Definitions API Use Case Guide](doc:product-type-api-use-case-guide).
 *
 * API version: 2020-09-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_type_definitions_v2020_09_01

// An Amazon product type with a definition available.
type ProductType struct {
	// The name of the Amazon product type.
	Name string `json:"name"`
	// The human-readable and localized description of the Amazon product type.
	DisplayName string `json:"displayName"`
	// The Amazon marketplace identifiers for which the product type definition is available.
	MarketplaceIds []string `json:"marketplaceIds"`
}
