/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Information that identifies an item.
type ItemIdentifier struct {
	// A marketplace identifier. Specifies the marketplace from which prices are returned.
	MarketplaceId string `json:"MarketplaceId"`
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN string `json:"ASIN,omitempty"`
	// The seller stock keeping unit (SKU) of the item.
	SellerSKU     string         `json:"SellerSKU,omitempty"`
	ItemCondition *ConditionType `json:"ItemCondition"`
}
