/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Schema for price info in `getPricing` response
type Price struct {
	// The status of the operation.
	Status string `json:"status"`
	// The seller stock keeping unit (SKU) of the item.
	SellerSKU string `json:"SellerSKU,omitempty"`
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN    string   `json:"ASIN,omitempty"`
	Product *Product `json:"Product,omitempty"`
}
