/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// The time range in which an item will likely be shipped once an order has been placed.
type DetailedShippingTimeType struct {
	// The minimum time, in hours, that the item will likely be shipped after the order has been placed.
	MinimumHours int64 `json:"minimumHours,omitempty"`
	// The maximum time, in hours, that the item will likely be shipped after the order has been placed.
	MaximumHours int64 `json:"maximumHours,omitempty"`
	// The date when the item will be available for shipping. Only displayed for items that are not currently available for shipping.
	AvailableDate string `json:"availableDate,omitempty"`
	// Indicates whether the item is available for shipping now, or on a known or an unknown date in the future. If known, the availableDate property indicates the date that the item will be available for shipping. Possible values: NOW, FUTURE_WITHOUT_DATE, FUTURE_WITH_DATE.
	AvailabilityType string `json:"availabilityType,omitempty"`
}
