/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0
// OfferCustomerType : Indicates whether the offer is a B2B or B2C offer
type OfferCustomerType string

// List of OfferCustomerType
const (
	B2_C_OfferCustomerType OfferCustomerType = "B2C"
	B2_B_OfferCustomerType OfferCustomerType = "B2B"
)
