/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// The response schema for the `getListingOffers` and `getItemOffers` operations.
type GetOffersResponse struct {
	Payload *GetOffersResult `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
