/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// An item.
type Product struct {
	Identifiers *IdentifierType `json:"Identifiers"`
	AttributeSets *[]interface{} `json:"AttributeSets,omitempty"`
	Relationships *[]interface{} `json:"Relationships,omitempty"`
	CompetitivePricing *CompetitivePricingType `json:"CompetitivePricing,omitempty"`
	SalesRankings *[]SalesRankType `json:"SalesRankings,omitempty"`
	Offers *[]OfferType `json:"Offers,omitempty"`
}
