/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// ItemCondition : Filters the offer listings to be considered based on item condition. Possible values: New, Used, Collectible, Refurbished, Club.
type ItemCondition string

// List of ItemCondition
const (
	NEW_ItemCondition         ItemCondition = "New"
	USED_ItemCondition        ItemCondition = "Used"
	COLLECTIBLE_ItemCondition ItemCondition = "Collectible"
	REFURBISHED_ItemCondition ItemCondition = "Refurbished"
	CLUB_ItemCondition        ItemCondition = "Club"
)
