/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// The number of offer listings with the specified condition.
type OfferListingCountType struct {
	// The number of offer listings.
	Count int32 `json:"Count"`
	// The condition of the item.
	Condition string `json:"condition"`
}
