/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Schema to identify an item by MarketPlaceId and ASIN.
type AsinIdentifier struct {
	// A marketplace identifier.
	MarketplaceId string `json:"MarketplaceId"`
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN string `json:"ASIN"`
}
