/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Schema for an individual `ListingOffersResponse`
type ListingOffersResponse struct {
	Request *ListingOffersRequestParams `json:"request,omitempty"`
	Headers *map[string]string          `json:"headers,omitempty"`
	Status  *GetOffersHttpStatusLine    `json:"status,omitempty"`
	Body    *GetOffersResponse          `json:"body"`
}
