/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Schema for an individual lowest price.
type LowestPriceType struct {
	// Indicates the condition of the item. For example: New, Used, Collectible, Refurbished, or Club.
	Condition string `json:"condition"`
	// Indicates whether the item is fulfilled by Amazon or by the seller.
	FulfillmentChannel string             `json:"fulfillmentChannel"`
	OfferType          *OfferCustomerType `json:"offerType,omitempty"`
	// Indicates at what quantity this price becomes active.
	QuantityTier         int32                 `json:"quantityTier,omitempty"`
	QuantityDiscountType *QuantityDiscountType `json:"quantityDiscountType,omitempty"`
	LandedPrice          *MoneyType            `json:"LandedPrice,omitempty"`
	ListingPrice         *MoneyType            `json:"ListingPrice"`
	Shipping             *MoneyType            `json:"Shipping,omitempty"`
	Points               *Points               `json:"Points,omitempty"`
}
