/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// List of request parameters that can be accepted by `ListingOffersRequest`
type ListingOffersRequestParams struct {
	// The seller stock keeping unit (SKU) of the item. This is the same SKU passed as a path parameter.
	SellerSKU string `json:"SellerSKU"`
	MarketplaceId string `json:"MarketplaceId"`
	ItemCondition *ItemCondition `json:"ItemCondition"`
	CustomerType *CustomerType `json:"CustomerType,omitempty"`
}
