/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

import (
	"time"
)

// Contains price information about the product, including the LowestPrices and BuyBoxPrices, the ListPrice, the SuggestedLowerPricePlusShipping, and NumberOfOffers and NumberOfBuyBoxEligibleOffers.
type Summary struct {
	// The number of unique offers contained in NumberOfOffers.
	TotalOfferCount                 int32              `json:"TotalOfferCount"`
	NumberOfOffers                  *[]OfferCountType  `json:"NumberOfOffers,omitempty"`
	LowestPrices                    *[]LowestPriceType `json:"LowestPrices,omitempty"`
	BuyBoxPrices                    *[]BuyBoxPriceType `json:"BuyBoxPrices,omitempty"`
	ListPrice                       *MoneyType         `json:"ListPrice,omitempty"`
	CompetitivePriceThreshold       *MoneyType         `json:"CompetitivePriceThreshold,omitempty"`
	SuggestedLowerPricePlusShipping *MoneyType         `json:"SuggestedLowerPricePlusShipping,omitempty"`
	SalesRankings                   *[]SalesRankType   `json:"SalesRankings,omitempty"`
	BuyBoxEligibleOffers            *[]OfferCountType  `json:"BuyBoxEligibleOffers,omitempty"`
	// When the status is ActiveButTooSoonForProcessing, this is the time when the offers will be available for processing.
	OffersAvailableTime time.Time `json:"OffersAvailableTime,omitempty"`
}
