/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Information about the seller's feedback, including the percentage of positive feedback, and the total number of ratings received.
type SellerFeedbackType struct {
	// The percentage of positive feedback for the seller in the past 365 days.
	SellerPositiveFeedbackRating float64 `json:"SellerPositiveFeedbackRating,omitempty"`
	// The number of ratings received about the seller.
	FeedbackCount int64 `json:"FeedbackCount"`
}
