/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Schema for competitive pricing information
type CompetitivePriceType struct {
	// The pricing model for each price that is returned.  Possible values:  * 1 - New Buy Box Price. * 2 - Used Buy Box Price.
	CompetitivePriceId string `json:"CompetitivePriceId"`
	Price *PriceType `json:"Price"`
	// Indicates the condition of the item whose pricing information is returned. Possible values are: New, Used, Collectible, Refurbished, or Club.
	Condition string `json:"condition,omitempty"`
	// Indicates the subcondition of the item whose pricing information is returned. Possible values are: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, or Other.
	Subcondition string `json:"subcondition,omitempty"`
	OfferType *OfferCustomerType `json:"offerType,omitempty"`
	// Indicates at what quantity this price becomes active.
	QuantityTier int32 `json:"quantityTier,omitempty"`
	QuantityDiscountType *QuantityDiscountType `json:"quantityDiscountType,omitempty"`
	// The seller identifier for the offer.
	SellerId string `json:"sellerId,omitempty"`
	//  Indicates whether or not the pricing information is for an offer listing that belongs to the requester. The requester is the seller associated with the SellerId that was submitted with the request. Possible values are: true and false.
	BelongsToRequester bool `json:"belongsToRequester,omitempty"`
}
