/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// The number of Amazon Points offered with the purchase of an item, and their monetary value.
type Points struct {
	// The number of points.
	PointsNumber int32 `json:"PointsNumber,omitempty"`
	PointsMonetaryValue *MoneyType `json:"PointsMonetaryValue,omitempty"`
}
