/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Contains pricing information that includes special pricing when buying in bulk.
type QuantityDiscountPriceType struct {
	// Indicates at what quantity this price becomes active.
	QuantityTier int32 `json:"quantityTier"`
	QuantityDiscountType *QuantityDiscountType `json:"quantityDiscountType"`
	ListingPrice *MoneyType `json:"listingPrice"`
}
