/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package product_pricing_v0

// Amazon Prime information.
type PrimeInformationType struct {
	// Indicates whether the offer is an Amazon Prime offer.
	IsPrime bool `json:"IsPrime"`
	// Indicates whether the offer is an Amazon Prime offer throughout the entire marketplace where it is listed.
	IsNationalPrime bool `json:"IsNationalPrime"`
}
