/*
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipment_invoicing_v0

// Payment transaction information
type PaymentInformation struct {
	PaymentMethod *PaymentMethodEnum `json:"PaymentMethod,omitempty"`
	// Government ID of acquirer
	AcquirerId string `json:"AcquirerId,omitempty"`
	// Credit card brand (if payment method is CreditCard)
	CardBrand    string `json:"CardBrand,omitempty"`
	PaymentValue *Money `json:"PaymentValue,omitempty"`
	// Authorization code for this payment
	AuthorizationCode string `json:"AuthorizationCode,omitempty"`
}
