/*
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shipment_invoicing_v0

// Tax information about the marketplace.
type MarketplaceTaxInfo struct {
	// The legal name of the company.
	CompanyLegalName string `json:"CompanyLegalName,omitempty"`
	// The country or region imposing the tax.
	TaxingRegion string `json:"TaxingRegion,omitempty"`
	TaxClassifications *[]TaxClassification `json:"TaxClassifications,omitempty"`
}
