/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// Indicates whether the carrier will pick up the package, and what fee is charged, if any.
type AvailableCarrierWillPickUpOption struct {
	CarrierWillPickUpOption *CarrierWillPickUpOption `json:"CarrierWillPickUpOption"`
	Charge *CurrencyAmount `json:"Charge"`
}
