/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

import (
	"time"
)

// Additional information required to purchase shipping.
type AdditionalSellerInput struct {
	// The data type of the additional information.
	DataType string `json:"DataType,omitempty"`
	// The value when the data type is string.
	ValueAsString string `json:"ValueAsString,omitempty"`
	// The value when the data type is boolean.
	ValueAsBoolean bool `json:"ValueAsBoolean,omitempty"`
	// The value when the data type is integer.
	ValueAsInteger   int32           `json:"ValueAsInteger,omitempty"`
	ValueAsTimestamp *time.Time      `json:"ValueAsTimestamp,omitempty"`
	ValueAsAddress   *Address        `json:"ValueAsAddress,omitempty"`
	ValueAsWeight    *Weight         `json:"ValueAsWeight,omitempty"`
	ValueAsDimension *Length         `json:"ValueAsDimension,omitempty"`
	ValueAsCurrency  *CurrencyAmount `json:"ValueAsCurrency,omitempty"`
}
