/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// InputTargetType : Indicates whether the additional seller input is at the item or shipment level.
type InputTargetType string

// List of InputTargetType
const (
	SHIPMENT_LEVEL_InputTargetType InputTargetType = "SHIPMENT_LEVEL"
	ITEM_LEVEL_InputTargetType     InputTargetType = "ITEM_LEVEL"
)
