/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0
import (
	"time"
)

// Shipment information required for requesting shipping service offers or for creating a shipment.
type ShipmentRequestDetails struct {
	AmazonOrderId string `json:"AmazonOrderId"`
	SellerOrderId string `json:"SellerOrderId,omitempty"`
	ItemList *[]Item `json:"ItemList"`
	ShipFromAddress *Address `json:"ShipFromAddress"`
	PackageDimensions *PackageDimensions `json:"PackageDimensions"`
	Weight *Weight `json:"Weight"`
	MustArriveByDate *time.Time `json:"MustArriveByDate,omitempty"`
	ShipDate *time.Time `json:"ShipDate,omitempty"`
	ShippingServiceOptions *ShippingServiceOptions `json:"ShippingServiceOptions"`
	LabelCustomization *LabelCustomization `json:"LabelCustomization,omitempty"`
}
