/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// Liquid volume.
type LiquidVolume struct {
	// The unit of measurement.
	Unit string `json:"Unit"`
	// The measurement value.
	Value float64 `json:"Value"`
}
