/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// A validation constraint.
type Constraint struct {
	// A regular expression.
	ValidationRegEx string `json:"ValidationRegEx,omitempty"`
	// A validation string.
	ValidationString string `json:"ValidationString"`
}
