/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// A carrier who is temporarily unavailable, most likely due to a service outage experienced by the carrier.
type TemporarilyUnavailableCarrier struct {
	// The name of the carrier.
	CarrierName string `json:"CarrierName"`
}
