/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0
// ShipmentStatus : The shipment status.
type ShipmentStatus string

// List of ShipmentStatus
const (
	PURCHASED_ShipmentStatus ShipmentStatus = "Purchased"
	REFUND_PENDING_ShipmentStatus ShipmentStatus = "RefundPending"
	REFUND_REJECTED_ShipmentStatus ShipmentStatus = "RefundRejected"
	REFUND_APPLIED_ShipmentStatus ShipmentStatus = "RefundApplied"
)
