/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0
// DeliveryExperienceType : The delivery confirmation level.
type DeliveryExperienceType string

// List of DeliveryExperienceType
const (
	DELIVERY_CONFIRMATION_WITH_ADULT_SIGNATURE_DeliveryExperienceType DeliveryExperienceType = "DeliveryConfirmationWithAdultSignature"
	DELIVERY_CONFIRMATION_WITH_SIGNATURE_DeliveryExperienceType DeliveryExperienceType = "DeliveryConfirmationWithSignature"
	DELIVERY_CONFIRMATION_WITHOUT_SIGNATURE_DeliveryExperienceType DeliveryExperienceType = "DeliveryConfirmationWithoutSignature"
	NO_TRACKING_DeliveryExperienceType DeliveryExperienceType = "NoTracking"
)
