/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// The available shipping service options.
type AvailableShippingServiceOptions struct {
	AvailableCarrierWillPickUpOptions *[]AvailableCarrierWillPickUpOption `json:"AvailableCarrierWillPickUpOptions"`
	AvailableDeliveryExperienceOptions *[]AvailableDeliveryExperienceOption `json:"AvailableDeliveryExperienceOptions"`
}
