/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package merchant_fulfillment_v0

// Details related to any dangerous goods or items that are shipped.
type DangerousGoodsDetails struct {
	// The specific UNID of the item being shipped.
	UnitedNationsRegulatoryId string `json:"UnitedNationsRegulatoryId,omitempty"`
	// The specific regulatory class of the shipped item.
	TransportationRegulatoryClass string `json:"TransportationRegulatoryClass,omitempty"`
	// The specific packaging group of the item being shipped.
	PackingGroup string `json:"PackingGroup,omitempty"`
	// The specific packing instruction of the item being shipped.
	PackingInstruction string `json:"PackingInstruction,omitempty"`
}
