/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The browse node review occurrence metrics.
type BrowseNodeAllOccurrence struct {
	// The percentage of reviews of the top 25 percent of products in the browse node that mention the topic.
	TopTwentyFivePercentProducts float32 `json:"topTwentyFivePercentProducts"`
	// The percentage of reviews of products in the browse node that mention the topic.
	AllProducts float32 `json:"allProducts"`
}
