/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The item review subtopic metrics.
type ItemReviewSubtopicMetrics struct {
	// The number of times that reviews mention the subtopic.
	NumberOfMentions int32 `json:"numberOfMentions"`
	// The percentage of reviews that mention the subtopic.
	OccurrencePercentage float32 `json:"occurrencePercentage"`
}
