/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The 10 most positive and most negative review topics for all items in a browse node.
type ItemReviewTrends struct {
	// A list of the most positive review topics. The percentage of reviews that contain the topic determines the topic's placement in the list. This value is `null` if there are not enough positive reviews for the specified ASIN.  **Max length:** 10
	PositiveTopics []ItemReviewTrend `json:"positiveTopics,omitempty"`
	// A list of the most negative review topics. The percentage of reviews that contain the topic determines the topic's placement in the list. This value is `null` if there are not enough negative reviews for the specified ASIN.  **Max length:** 10
	NegativeTopics []ItemReviewTrend `json:"negativeTopics,omitempty"`
}
