/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The trend of review topic metrics for the requested item.
type ItemReviewTrend struct {
	// The name of the item review topic.
	Topic string `json:"topic"`
	// The item's review trend metrics for the past six months.
	TrendMetrics []ItemReviewTrendPoint `json:"trendMetrics"`
}
