/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// Topics from returns for all items in a browse node.
type BrowseNodeReturnTopics struct {
	// The name of the return feedback topic .
	Topic string `json:"topic"`
	BrowseNodeMetrics *BrowseNodeTrendMetrics `json:"browseNodeMetrics"`
}
