/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The effects of a topic on the star ratings in a browse node.
type BrowseNodeAllStarRatingImpact struct {
	// The effect of the topic on the star rating of the top 25 percent of products in the browse node. This value can be positive or negative.
	TopTwentyFivePercentProducts float32 `json:"topTwentyFivePercentProducts"`
	// The effect of the topic on the star rating of all products in the browse node. This value can be positive or negative.
	AllProducts float32 `json:"allProducts"`
}
