/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The response for the `getItemReviewTopics` operation.
type ItemReviewTopicsResponse struct {
	// The requested ASIN. The Amazon Standard Identification Number (ASIN) is the unique identifier of a product within a marketplace.
	Asin string `json:"asin"`
	// The product title of the requested ASIN.
	ItemName string `json:"itemName"`
	// The requested marketplace id.
	MarketplaceId string `json:"marketplaceId"`
	// The two digit country code of the requested marketplace id, in ISO 3166-1 alpha-2 format.
	CountryCode string            `json:"countryCode"`
	DateRange   *DateRange        `json:"dateRange"`
	Topics      *ItemReviewTopics `json:"topics"`
}
