/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customer_feedback_v2024_06_01

// The item review topic metrics.
type ItemReviewTopicMetrics struct {
	// The number of times that reviews mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
	NumberOfMentions int32 `json:"numberOfMentions,omitempty"`
	// The percentage of customer reviews that mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
	OccurrencePercentage float32 `json:"occurrencePercentage,omitempty"`
	// The effect of the topic on the star rating of the ASIN. This value can be positive or negative. This value is `null` if the topic does't affect the star rating of the ASIN.
	StarRatingImpact float32 `json:"starRatingImpact,omitempty"`
}
