/*
 * Selling Partner API for Listings Restrictions
 *
 * The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).
 *
 * API version: 2021-08-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package listings_restrictions_v2021_08_01

// A link to resources related to a listing restriction.
type Link struct {
	// The URI of the related resource.
	Resource string `json:"resource"`
	// The HTTP verb used to interact with the related resource.
	Verb string `json:"verb"`
	// The title of the related resource.
	Title string `json:"title,omitempty"`
	// The media type of the related resource.
	Type_ string `json:"type,omitempty"`
}
