/*
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_payments_v1

// An amount of money, including units in the form of currency.
type Money struct {
	// Three digit currency code in ISO 4217 format.
	CurrencyCode string `json:"currencyCode"`
	Amount string `json:"amount"`
}
