/*
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_payments_v1

// Provides the details of the items in this invoice.
type InvoiceItem struct {
	// Numbering of the item on the purchase order. The first item will be 1, the second 2, and so on.
	ItemSequenceNumber string `json:"itemSequenceNumber"`
	// Buyer's standard identification number (ASIN) of an item.
	BuyerProductIdentifier string `json:"buyerProductIdentifier,omitempty"`
	// The vendor selected product identification of the item.
	VendorProductIdentifier string `json:"vendorProductIdentifier,omitempty"`
	InvoicedQuantity *ItemQuantity `json:"invoicedQuantity"`
	NetCost *Money `json:"netCost"`
	// The purchase order number for this order. Formatting Notes: 8-character alpha-numeric code.
	PurchaseOrderNumber string `json:"purchaseOrderNumber"`
	// The vendor's order number for this order.
	VendorOrderNumber string `json:"vendorOrderNumber,omitempty"`
	// Harmonized System of Nomenclature (HSN) tax code. The HSN number cannot contain alphabets.
	HsnCode string `json:"hsnCode,omitempty"`
	// Individual tax details per line item.
	TaxDetails []TaxDetail `json:"taxDetails,omitempty"`
	// Individual charge details per line item.
	ChargeDetails []ChargeDetails `json:"chargeDetails,omitempty"`
}
