/*
 * The Selling Partner API for Sellers
 *
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sellers_v1

// Information about an Amazon marketplace where a seller can list items and customers can view and purchase items.
type Marketplace struct {
	// The encrypted marketplace value.
	Id string `json:"id"`
	// The marketplace name.
	Name string `json:"name"`
	// The ISO 3166-1 alpha-2 format country code of the marketplace.
	CountryCode string `json:"countryCode"`
	// The ISO 4217 format currency code of the marketplace.
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`
	// The ISO 639-1 format language code of the marketplace.
	DefaultLanguageCode string `json:"defaultLanguageCode"`
	// The domain name of the marketplace.
	DomainName string `json:"domainName"`
}
