/*
 * The Selling Partner API for Sellers
 *
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sellers_v1

// Represents an address
type Address struct {
	// Street address information.
	AddressLine1 string `json:"addressLine1"`
	// Additional street address information.
	AddressLine2 string `json:"addressLine2,omitempty"`
	// The country code in two-character ISO 3166-1 alpha-2 format.
	CountryCode string `json:"countryCode"`
	// The state or province code.
	StateOrProvinceCode string `json:"stateOrProvinceCode,omitempty"`
	// The city.
	City string `json:"city,omitempty"`
	// The postal code.
	PostalCode string `json:"postalCode,omitempty"`
}
