/*
 * The Selling Partner API for Sellers
 *
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sellers_v1

// The response schema for the `getMarketplaceParticipations` operation.
type GetMarketplaceParticipationsResponse struct {
	Payload *[]MarketplaceParticipation `json:"payload,omitempty"`
	Errors  *[]ModelError               `json:"errors,omitempty"`
}
