/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * API version: 2024-03-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package seller_wallet_v2024_03_01
// BankAccountOwnershipType : Represents destination bank account's ownership type.
type BankAccountOwnershipType string

// List of BankAccountOwnershipType
const (
	THIRD_PARTY_BankAccountOwnershipType BankAccountOwnershipType = "THIRD_PARTY"
	SELF_BankAccountOwnershipType BankAccountOwnershipType = "SELF"
	GOVERNMENT_BankAccountOwnershipType BankAccountOwnershipType = "GOVERNMENT"
)
