/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * API version: 2024-03-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package seller_wallet_v2024_03_01

// Request body to initiate a scheduled transfer from a SW bank account to another customer defined bank account 
type TransferScheduleRequest struct {
	// The unique identifier of the source Amazon SW bank account from where the money needs to be debited 
	SourceAccountId string `json:"sourceAccountId"`
	// Represents 3 letter currency code in ISO 4217 standard format of the source payment method country 
	SourceCurrencyCode string `json:"sourceCurrencyCode"`
	// Optional field to specify the unique identifier of the destination bank account where the money needs to be deposited 
	DestinationAccountId string `json:"destinationAccountId"`
	DestinationTransactionInstrument *TransactionInstrumentDetails `json:"destinationTransactionInstrument"`
	TransactionType *TransactionType `json:"transactionType"`
	TransferScheduleInformation *TransferScheduleInformation `json:"transferScheduleInformation"`
	PaymentPreference *PaymentPreference `json:"paymentPreference"`
	TransferScheduleStatus *TransferScheduleStatus `json:"transferScheduleStatus,omitempty"`
}
