/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * API version: 2024-03-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package seller_wallet_v2024_03_01

// Parameters containing information of the expression that defines when the schedule runs. The following formats are supported.
type ScheduleExpression struct {
	ScheduleExpressionType *ScheduleExpressionType `json:"scheduleExpressionType"`
	RecurringFrequency     *RecurringFrequency     `json:"recurringFrequency,omitempty"`
}
