/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v2021_12_28

// Details of the shipment label.
type LabelData struct {
	// Identifier for the package. The first package will be 001, the second 002, and so on. This number is used as a reference to refer to this package from the pallet level.
	PackageIdentifier string `json:"packageIdentifier,omitempty"`
	// Package tracking identifier from the shipping carrier.
	TrackingNumber string `json:"trackingNumber,omitempty"`
	// Ship method to be used for shipping the order. Amazon defines Ship Method Codes indicating shipping carrier and shipment service level. Ship Method Codes are case and format sensitive. The same ship method code should returned on the shipment confirmation. Note that the Ship Method Codes are vendor specific and will be provided to each vendor during the implementation.
	ShipMethod string `json:"shipMethod,omitempty"`
	// Shipping method name for internal reference.
	ShipMethodName string `json:"shipMethodName,omitempty"`
	// This field will contain the Base64 string of the shipment label content.
	Content string `json:"content"`
}
