/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v2021_12_28

// Represents a customer invoice associated with a purchase order.
type CustomerInvoice struct {
	// The purchase order number for this order.
	PurchaseOrderNumber string `json:"purchaseOrderNumber"`
	// The Base64 customer invoice.
	Content string `json:"content"`
}
