/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v2021_12_28

// The request schema for the `submitShipmentStatusUpdates` operation.
type SubmitShipmentStatusUpdatesRequest struct {
	// Contains a list of one or more `ShipmentStatusUpdate` objects. Each `ShipmentStatusUpdate` object represents an update to the status of a specific shipment.
	ShipmentStatusUpdates []ShipmentStatusUpdate `json:"shipmentStatusUpdates,omitempty"`
}
