/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v2021_12_28
// CarrierId : The unique carrier code for the carrier for whom container labels are requested.
type CarrierId string

// List of CarrierId
const (
	SWA_CarrierId CarrierId = "SWA"
)
