/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_shipping_v2021_12_28

// Packing slip information.
type PackingSlip struct {
	// Purchase order number of the shipment that the packing slip is for.
	PurchaseOrderNumber string `json:"purchaseOrderNumber"`
	// A Base64 string of the packing slip PDF.
	Content string `json:"content"`
	// The format of the file such as PDF, JPEG etc.
	ContentType string `json:"contentType,omitempty"`
}
