/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Contains information about a pallet that is used in the inbound plan. The pallet is a container that holds multiple items or boxes.
type Pallet struct {
	Dimensions *Dimensions `json:"dimensions,omitempty"`
	// Primary key to uniquely identify a Package (Box or Pallet).
	PackageId string `json:"packageId"`
	// The number of containers where all other properties like weight or dimensions are identical.
	Quantity     int32         `json:"quantity,omitempty"`
	Stackability *Stackability `json:"stackability,omitempty"`
	Weight       *Weight       `json:"weight,omitempty"`
}
