/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20
import (
	"time"
)

// A packing option contains a set of pack groups plus additional information about the packing option, such as any discounts or fees if it's selected.
type PackingOption struct {
	// Discount for the offered option.
	Discounts []Incentive `json:"discounts"`
	// The time at which this packing option is no longer valid. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
	Expiration time.Time `json:"expiration,omitempty"`
	// Fee for the offered option.
	Fees []Incentive `json:"fees"`
	// Packing group IDs.
	PackingGroups []string `json:"packingGroups"`
	// Identifier of a packing option.
	PackingOptionId string `json:"packingOptionId"`
	// The status of the packing option. Possible values: `OFFERED`, `ACCEPTED`, `EXPIRED`.
	Status string `json:"status"`
	// A list of possible configurations for this option.
	SupportedConfigurations []PackingConfiguration `json:"supportedConfigurations"`
	// **This field is deprecated**. Use the `shippingRequirements` property under `supportedConfigurations` instead. List of supported shipping modes.
	SupportedShippingConfigurations []ShippingConfiguration `json:"supportedShippingConfigurations"`
}
