/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Representation of a location used within the inbounding experience.
type Region struct {
	// ISO 3166 standard alpha-2 country code.
	CountryCode string `json:"countryCode,omitempty"`
	// State.
	State string `json:"state,omitempty"`
	// An identifier for a warehouse, such as a FC, IXD, upstream storage.
	WarehouseId string `json:"warehouseId,omitempty"`
}
