/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Contains information about a box that is used in the inbound plan. The box is a container that holds multiple items.
type Box struct {
	// The ID provided by Amazon that identifies a given box. This ID is comprised of the external shipment ID (which is generated after transportation has been confirmed) and the index of the box.
	BoxId                    string                       `json:"boxId,omitempty"`
	ContentInformationSource *BoxContentInformationSource `json:"contentInformationSource,omitempty"`
	DestinationRegion        *Region                      `json:"destinationRegion,omitempty"`
	Dimensions               *Dimensions                  `json:"dimensions,omitempty"`
	// The external identifier for this container / box.
	ExternalContainerIdentifier string `json:"externalContainerIdentifier,omitempty"`
	// Type of the external identifier used. Can be: `AMAZON`, `SSCC`.
	ExternalContainerIdentifierType string `json:"externalContainerIdentifierType,omitempty"`
	// Items contained within the box.
	Items []Item `json:"items,omitempty"`
	// Primary key to uniquely identify a Package (Box or Pallet).
	PackageId string `json:"packageId"`
	// The number of containers where all other properties like weight or dimensions are identical.
	Quantity int32 `json:"quantity,omitempty"`
	// Template name of the box.
	TemplateName string  `json:"templateName,omitempty"`
	Weight       *Weight `json:"weight,omitempty"`
}
