/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Contains item identifiers and related tax information.
type ComplianceDetail struct {
	// The Amazon Standard Identification Number, which identifies the detail page identifier.
	Asin string `json:"asin,omitempty"`
	// The Fulfillment Network SKU, which identifies a real fulfillable item with catalog data and condition.
	Fnsku string `json:"fnsku,omitempty"`
	// The merchant SKU, a merchant-supplied identifier for a specific SKU.
	Msku       string      `json:"msku,omitempty"`
	TaxDetails *TaxDetails `json:"taxDetails,omitempty"`
}
