/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Contains information pertaining to a transportation option and the related carrier.
type TransportationOption struct {
	Carrier            *Carrier            `json:"carrier"`
	CarrierAppointment *CarrierAppointment `json:"carrierAppointment,omitempty"`
	// Identifies a list of preconditions for confirming the transportation option.
	Preconditions []string `json:"preconditions"`
	Quote         *Quote   `json:"quote,omitempty"`
	// Identifier of a shipment. A shipment contains the boxes and units being inbounded.
	ShipmentId string `json:"shipmentId"`
	// Mode of shipment transportation that this option will provide.  Possible values: `GROUND_SMALL_PARCEL`, `FREIGHT_LTL`, `FREIGHT_FTL_PALLET`, `FREIGHT_FTL_NONPALLET`, `OCEAN_LCL`, `OCEAN_FCL`, `AIR_SMALL_PARCEL`, `AIR_SMALL_PARCEL_EXPRESS`.
	ShippingMode string `json:"shippingMode"`
	// Shipping program for the option. Possible values: `AMAZON_PARTNERED_CARRIER`, `USE_YOUR_OWN_CARRIER`.
	ShippingSolution string `json:"shippingSolution"`
	// Identifier of a transportation option. A transportation option represent one option for how to send a shipment.
	TransportationOptionId string `json:"transportationOptionId"`
}
