/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// The `createInboundPlan` request.
type CreateInboundPlanRequest struct {
	// Marketplaces where the items need to be shipped to. Currently only one marketplace can be selected in this request.
	DestinationMarketplaces []string `json:"destinationMarketplaces"`
	// Items included in this plan.
	Items []ItemInput `json:"items"`
	// Name for the Inbound Plan. If one isn't provided, a default name will be provided.
	Name string `json:"name,omitempty"`
	SourceAddress *AddressInput `json:"sourceAddress"`
}
