/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20
// OperationStatus : The status of an operation.
type OperationStatus string

// List of OperationStatus
const (
	SUCCESS_OperationStatus OperationStatus = "SUCCESS"
	FAILED_OperationStatus OperationStatus = "FAILED"
	IN_PROGRESS_OperationStatus OperationStatus = "IN_PROGRESS"
)
