/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20
// BoxContentInformationSource : Indication of how box content is meant to be provided.
type BoxContentInformationSource string

// List of BoxContentInformationSource
const (
	BOX_CONTENT_PROVIDED_BoxContentInformationSource BoxContentInformationSource = "BOX_CONTENT_PROVIDED"
	MANUAL_PROCESS_BoxContentInformationSource BoxContentInformationSource = "MANUAL_PROCESS"
	BARCODE_2_D_BoxContentInformationSource BoxContentInformationSource = "BARCODE_2D"
)
