/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

import (
	"time"
)

// Preview of the changes that will be applied to the shipment.
type ContentUpdatePreview struct {
	// Identifier of a content update preview.
	ContentUpdatePreviewId string `json:"contentUpdatePreviewId"`
	// The time at which the content update expires. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
	Expiration           time.Time             `json:"expiration"`
	RequestedUpdates     *RequestedUpdates     `json:"requestedUpdates"`
	TransportationOption *TransportationOption `json:"transportationOption"`
}
