/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Specific details to identify a place.
type AddressInput struct {
	// Street address information.
	AddressLine1 string `json:"addressLine1"`
	// Additional street address information.
	AddressLine2 string `json:"addressLine2,omitempty"`
	// The city.
	City string `json:"city"`
	// The name of the business.
	CompanyName string `json:"companyName,omitempty"`
	// The country code in two-character ISO 3166-1 alpha-2 format.
	CountryCode string `json:"countryCode"`
	// The district or county.
	DistrictOrCounty string `json:"districtOrCounty,omitempty"`
	// The email address.
	Email string `json:"email,omitempty"`
	// The name of the individual who is the primary contact.
	Name string `json:"name"`
	// The phone number.
	PhoneNumber string `json:"phoneNumber"`
	// The postal code.
	PostalCode string `json:"postalCode"`
	// The state or province code.
	StateOrProvinceCode string `json:"stateOrProvinceCode,omitempty"`
}
