/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// Input information for a given box.
type BoxInput struct {
	ContentInformationSource *BoxContentInformationSource `json:"contentInformationSource"`
	Dimensions *Dimensions `json:"dimensions"`
	// The items and their quantity in the box. This must be empty if the box `contentInformationSource` is `BARCODE_2D` or `MANUAL_PROCESS`.
	Items []ItemInput `json:"items,omitempty"`
	// The number of containers where all other properties like weight or dimensions are identical.
	Quantity int32 `json:"quantity"`
	Weight *Weight `json:"weight"`
}
