/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

import (
	"time"
)

// A light-weight inbound plan.
type InboundPlanSummary struct {
	// The time at which the inbound plan was created. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
	CreatedAt time.Time `json:"createdAt"`
	// Identifier of an inbound plan.
	InboundPlanId string `json:"inboundPlanId"`
	// The time at which the inbound plan was last updated. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// A list of marketplace IDs.
	MarketplaceIds []string `json:"marketplaceIds"`
	// Human-readable name of the inbound plan.
	Name          string   `json:"name"`
	SourceAddress *Address `json:"sourceAddress"`
	// The current status of the inbound plan. Possible values: `ACTIVE`, `VOIDED`, `SHIPPED`, `ERRORED`.
	Status string `json:"status"`
}
