/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * API version: 2024-03-20
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v2024_03_20

// The `generateTransportationOptions` request.
type GenerateTransportationOptionsRequest struct {
	// The placement option to generate transportation options for.
	PlacementOptionId string `json:"placementOptionId"`
	// List of shipment transportation configurations.
	ShipmentTransportationConfigurations []ShipmentTransportationConfiguration `json:"shipmentTransportationConfigurations"`
}
