/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// PrepGuidance : Item preparation instructions.
type PrepGuidance string

// List of PrepGuidance
const (
	CONSULT_HELP_DOCUMENTS_PrepGuidance      PrepGuidance = "ConsultHelpDocuments"
	NO_ADDITIONAL_PREP_REQUIRED_PrepGuidance PrepGuidance = "NoAdditionalPrepRequired"
	SEE_PREP_INSTRUCTIONS_LIST_PrepGuidance  PrepGuidance = "SeePrepInstructionsList"
)
