/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0
// ErrorReason : The reason that the ASIN is invalid.
type ErrorReason string

// List of ErrorReason
const (
	DOES_NOT_EXIST_ErrorReason ErrorReason = "DoesNotExist"
	INVALID_ASIN_ErrorReason ErrorReason = "InvalidASIN"
)
