/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// Specific details to identify a place.
type Address struct {
	// Name of the individual or business.
	Name string `json:"Name"`
	// The street address information.
	AddressLine1 string `json:"AddressLine1"`
	// Additional street address information, if required.
	AddressLine2 string `json:"AddressLine2,omitempty"`
	// The district or county.
	DistrictOrCounty string `json:"DistrictOrCounty,omitempty"`
	// The city.
	City string `json:"City"`
	// The state or province code.  If state or province codes are used in your marketplace, it is recommended that you include one with your request. This helps Amazon to select the most appropriate Amazon fulfillment center for your inbound shipment plan.
	StateOrProvinceCode string `json:"StateOrProvinceCode"`
	// The country code in two-character ISO 3166-1 alpha-2 format.
	CountryCode string `json:"CountryCode"`
	// The postal code.  If postal codes are used in your marketplace, we recommended that you include one with your request. This helps Amazon select the most appropriate Amazon fulfillment center for the inbound shipment plan.
	PostalCode string `json:"PostalCode"`
}
