/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// Download URL for the bill of lading.
type BillOfLadingDownloadUrl struct {
	// URL to download the bill of lading for the package. Note: The URL will only be valid for 15 seconds
	DownloadURL string `json:"DownloadURL,omitempty"`
}
