/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// The response schema for the getBillOfLading operation.
type GetBillOfLadingResponse struct {
	Payload *BillOfLadingDownloadUrl `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
