/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// The monetary value.
type Amount struct {
	CurrencyCode *CurrencyCode `json:"CurrencyCode"`
	Value float64 `json:"Value"`
}
