/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// Item preparation instructions to help with item sourcing decisions.
type AsinPrepInstructions struct {
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN string `json:"ASIN,omitempty"`
	BarcodeInstruction *BarcodeInstruction `json:"BarcodeInstruction,omitempty"`
	PrepGuidance *PrepGuidance `json:"PrepGuidance,omitempty"`
	PrepInstructionList *[]PrepInstruction `json:"PrepInstructionList,omitempty"`
}
