/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_inbound_v0

// Information about the seller's inbound shipments. Returned by the listInboundShipments operation.
type InboundShipmentInfo struct {
	// The shipment identifier submitted in the request.
	ShipmentId string `json:"ShipmentId,omitempty"`
	// The name for the inbound shipment.
	ShipmentName    string   `json:"ShipmentName,omitempty"`
	ShipFromAddress *Address `json:"ShipFromAddress"`
	// An Amazon fulfillment center identifier created by Amazon.
	DestinationFulfillmentCenterId string          `json:"DestinationFulfillmentCenterId,omitempty"`
	ShipmentStatus                 *ShipmentStatus `json:"ShipmentStatus,omitempty"`
	LabelPrepType                  *LabelPrepType  `json:"LabelPrepType,omitempty"`
	// Indicates whether or not an inbound shipment contains case-packed boxes. When AreCasesRequired = true for an inbound shipment, all items in the inbound shipment must be case packed.
	AreCasesRequired        bool                   `json:"AreCasesRequired"`
	ConfirmedNeedByDate     string                 `json:"ConfirmedNeedByDate,omitempty"`
	BoxContentsSource       *BoxContentsSource     `json:"BoxContentsSource,omitempty"`
	EstimatedBoxContentsFee *BoxContentsFeeDetails `json:"EstimatedBoxContentsFee,omitempty"`
}
