/*
 * The Selling Partner API for Transfers.
 *
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_01_transfers

// The expiration date of the card used for payment. If the payment method is not `card`, the expiration date is `null`.
type ExpiryDate struct {
	// The month the card expires expressed as a number from `1` to `12`.
	Month string `json:"month,omitempty"`
	// Year
	Year string `json:"year,omitempty"`
}
