/*
 * The Selling Partner API for Transfers.
 *
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_01_transfers

// The request schema for the `initiatePayout` operation.
type InitiatePayoutRequest struct {
	MarketplaceId string `json:"marketplaceId"`
	// The account type in the selected marketplace for which a payout must be initiated. For supported EU marketplaces, the only account type is `Standard Orders`.
	AccountType string `json:"accountType"`
}
