/*
 * The Selling Partner API for Transfers.
 *
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * API version: 2024-06-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package finances_v2024_06_01_transfers

// PaymentMethodType : The type of payment method.
type PaymentMethodType string

// List of PaymentMethodType
const (
	BANK_ACCOUNT_PaymentMethodType  PaymentMethodType = "BANK_ACCOUNT"
	CARD_PaymentMethodType          PaymentMethodType = "CARD"
	SELLER_WALLET_PaymentMethodType PaymentMethodType = "SELLER_WALLET"
)
