/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v2021_12_28
import (
	"time"
)

// Dates for the scheduled delivery shipments.
type ScheduledDeliveryShipment struct {
	// Scheduled delivery service type.
	ScheduledDeliveryServiceType string `json:"scheduledDeliveryServiceType,omitempty"`
	// Earliest nominated delivery date for the scheduled delivery.
	EarliestNominatedDeliveryDate time.Time `json:"earliestNominatedDeliveryDate,omitempty"`
	// Latest nominated delivery date for the scheduled delivery.
	LatestNominatedDeliveryDate time.Time `json:"latestNominatedDeliveryDate,omitempty"`
}
