/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v2021_12_28

// The response schema for the submitAcknowledgement operation.
type SubmitAcknowledgementResponse struct {
	Payload *TransactionId `json:"payload,omitempty"`
	Errors  *ErrorList     `json:"errors,omitempty"`
}
