/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v2021_12_28

// Gift details for the item.
type GiftDetails struct {
	// Gift message to be printed in shipment.
	GiftMessage string `json:"giftMessage,omitempty"`
	// Gift wrap identifier for the gift wrapping, if any.
	GiftWrapId string `json:"giftWrapId,omitempty"`
}
