/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * API version: 2021-12-28
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vendor_direct_fulfillment_orders_v2021_12_28

// The tax details for the order. _Note:_ Amazon calculates tax on the list price (Amazon retail price).
type TaxDetails struct {
	TaxRate       string `json:"taxRate,omitempty"`
	TaxAmount     *Money `json:"taxAmount"`
	TaxableAmount *Money `json:"taxableAmount,omitempty"`
	// Tax type.
	Type_ string `json:"type,omitempty"`
}
