/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package catalog_items_v0

type ListCatalogCategoriesResponse struct {
	Payload *[]Categories `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
