/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

import (
	"time"
)

// Package information for a shipment in a fulfillment order.
type FulfillmentShipmentPackage struct {
	// Identifies a package in a shipment.
	PackageNumber int32 `json:"packageNumber"`
	// Identifies the carrier who will deliver the shipment to the recipient.
	CarrierCode string `json:"carrierCode"`
	// The tracking number, if provided, can be used to obtain tracking and delivery information.
	TrackingNumber string `json:"trackingNumber,omitempty"`
	// The Amazon fulfillment tracking number, if provided, can be used to obtain tracking and delivery information.
	AmazonFulfillmentTrackingNumber string               `json:"amazonFulfillmentTrackingNumber,omitempty"`
	EstimatedArrivalDate            *time.Time           `json:"estimatedArrivalDate,omitempty"`
	LockerDetails                   *LockerDetails       `json:"lockerDetails,omitempty"`
	DeliveryInformation             *DeliveryInformation `json:"deliveryInformation,omitempty"`
}
