/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// A physical address with varying degrees of precision. A more precise address can provide more accurate results than country code and postal code alone.
type VariablePrecisionAddress struct {
	// The first line of the address.
	AddressLine1 string `json:"addressLine1,omitempty"`
	// Additional address information, if required.
	AddressLine2 string `json:"addressLine2,omitempty"`
	// Additional address information, if required.
	AddressLine3 string `json:"addressLine3,omitempty"`
	// The city where the person, business, or institution is located. This property should not be used in Japan.
	City string `json:"city,omitempty"`
	// The district or county where the person, business, or institution is located.
	DistrictOrCounty string `json:"districtOrCounty,omitempty"`
	// The state or region where the person, business or institution is located.
	StateOrRegion string `json:"stateOrRegion,omitempty"`
	// The postal code of the address.
	PostalCode string `json:"postalCode"`
	// The two digit country code. In ISO 3166-1 alpha-2 format.
	CountryCode string `json:"countryCode"`
}
