/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01
import (
	"time"
)

// Delivery and item information for a shipment in a fulfillment order preview.
type FulfillmentPreviewShipment struct {
	EarliestShipDate *time.Time `json:"earliestShipDate,omitempty"`
	LatestShipDate *time.Time `json:"latestShipDate,omitempty"`
	EarliestArrivalDate *time.Time `json:"earliestArrivalDate,omitempty"`
	LatestArrivalDate *time.Time `json:"latestArrivalDate,omitempty"`
	// Provides additional insight into the shipment timeline when exact delivery dates are not able to be precomputed.
	ShippingNotes []string `json:"shippingNotes,omitempty"`
	FulfillmentPreviewItems *[]FulfillmentPreviewItem `json:"fulfillmentPreviewItems"`
}
