/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// ReturnItemDisposition : The condition of the return item when received by an Amazon fulfillment center.
type ReturnItemDisposition string

// List of ReturnItemDisposition
const (
	SELLABLE_ReturnItemDisposition          ReturnItemDisposition = "Sellable"
	DEFECTIVE_ReturnItemDisposition         ReturnItemDisposition = "Defective"
	CUSTOMER_DAMAGED_ReturnItemDisposition  ReturnItemDisposition = "CustomerDamaged"
	CARRIER_DAMAGED_ReturnItemDisposition   ReturnItemDisposition = "CarrierDamaged"
	FULFILLER_DAMAGED_ReturnItemDisposition ReturnItemDisposition = "FulfillerDamaged"
)
