/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// The request body schema for the `getFulfillmentPreview` operation.
type GetFulfillmentPreviewRequest struct {
	// The marketplace the fulfillment order is placed against.
	MarketplaceId string `json:"marketplaceId,omitempty"`
	Address *Address `json:"address"`
	Items *[]GetFulfillmentPreviewItem `json:"items"`
	ShippingSpeedCategories *[]ShippingSpeedCategory `json:"shippingSpeedCategories,omitempty"`
	// When true, returns all fulfillment order previews both for COD and not for COD. Otherwise, returns only fulfillment order previews that are not for COD.
	IncludeCODFulfillmentPreview bool `json:"includeCODFulfillmentPreview,omitempty"`
	// When true, returns the `ScheduledDeliveryInfo` response object, which contains the available delivery windows for a Scheduled Delivery. The `ScheduledDeliveryInfo` response object can only be returned for fulfillment order previews with `ShippingSpeedCategories` equal to `ScheduledDelivery`.
	IncludeDeliveryWindows bool `json:"includeDeliveryWindows,omitempty"`
	// A list of features and their fulfillment policies to apply to the order.
	FeatureConstraints []FeatureSettings `json:"featureConstraints,omitempty"`
}
