/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01
import (
	"time"
)

// Item information for a fulfillment order.
type FulfillmentOrderItem struct {
	// The seller SKU of the item.
	SellerSku string `json:"sellerSku"`
	// A fulfillment order item identifier submitted with a call to the `createFulfillmentOrder` operation.
	SellerFulfillmentOrderItemId string `json:"sellerFulfillmentOrderItemId"`
	Quantity int32 `json:"quantity"`
	// A message to the gift recipient, if applicable.
	GiftMessage string `json:"giftMessage,omitempty"`
	// Item-specific text that displays in recipient-facing materials such as the outbound shipment packing slip.
	DisplayableComment string `json:"displayableComment,omitempty"`
	// Amazon's fulfillment network SKU of the item.
	FulfillmentNetworkSku string `json:"fulfillmentNetworkSku,omitempty"`
	// Indicates whether the item is sellable or unsellable.
	OrderItemDisposition string `json:"orderItemDisposition,omitempty"`
	CancelledQuantity int32 `json:"cancelledQuantity"`
	UnfulfillableQuantity int32 `json:"unfulfillableQuantity"`
	EstimatedShipDate *time.Time `json:"estimatedShipDate,omitempty"`
	EstimatedArrivalDate *time.Time `json:"estimatedArrivalDate,omitempty"`
	PerUnitPrice *Money `json:"perUnitPrice,omitempty"`
	PerUnitTax *Money `json:"perUnitTax,omitempty"`
	PerUnitDeclaredValue *Money `json:"perUnitDeclaredValue,omitempty"`
}
