/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

import (
	"time"
)

// The attributes related to the payment made from customer to seller for this order.
type PaymentInformation struct {
	// The transaction identifier of this payment.
	PaymentTransactionId string `json:"paymentTransactionId"`
	// The transaction mode of this payment.
	PaymentMode string     `json:"paymentMode"`
	PaymentDate *time.Time `json:"paymentDate"`
}
