/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01
// FulfillmentOrderStatus : The current status of the fulfillment order.
type FulfillmentOrderStatus string

// List of FulfillmentOrderStatus
const (
	NEW_FulfillmentOrderStatus FulfillmentOrderStatus = "New"
	RECEIVED_FulfillmentOrderStatus FulfillmentOrderStatus = "Received"
	PLANNING_FulfillmentOrderStatus FulfillmentOrderStatus = "Planning"
	PROCESSING_FulfillmentOrderStatus FulfillmentOrderStatus = "Processing"
	CANCELLED_FulfillmentOrderStatus FulfillmentOrderStatus = "Cancelled"
	COMPLETE_FulfillmentOrderStatus FulfillmentOrderStatus = "Complete"
	COMPLETE_PARTIALLED_FulfillmentOrderStatus FulfillmentOrderStatus = "CompletePartialled"
	UNFULFILLABLE_FulfillmentOrderStatus FulfillmentOrderStatus = "Unfulfillable"
	INVALID_FulfillmentOrderStatus FulfillmentOrderStatus = "Invalid"
)
