/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// Item information for a shipment in a fulfillment order preview.
type FulfillmentPreviewItem struct {
	// The seller SKU of the item.
	SellerSku string `json:"sellerSku"`
	Quantity int32 `json:"quantity"`
	// A fulfillment order item identifier that the seller created with a call to the `createFulfillmentOrder` operation.
	SellerFulfillmentOrderItemId string `json:"sellerFulfillmentOrderItemId"`
	EstimatedShippingWeight *Weight `json:"estimatedShippingWeight,omitempty"`
	// The method used to calculate the estimated shipping weight.
	ShippingWeightCalculationMethod string `json:"shippingWeightCalculationMethod,omitempty"`
}
