/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// A return reason code, a description, and an optional description translation.
type ReasonCodeDetails struct {
	// A code that indicates a valid return reason.
	ReturnReasonCode string `json:"returnReasonCode"`
	// A human readable description of the return reason code.
	Description string `json:"description"`
	// A translation of the description. The translation is in the language specified in the `language` request parameter.
	TranslatedDescription string `json:"translatedDescription,omitempty"`
}
