/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// Localized messaging for a delivery offering.
type DeliveryMessage struct {
	// The message content for a delivery offering.
	Text string `json:"text,omitempty"`
	// The locale for the message (e.g., `en_US`).
	Locale string `json:"locale,omitempty"`
}
