/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01
import (
	"time"
)

// The request body schema for the `createFulfillmentOrder` operation.
type CreateFulfillmentOrderRequest struct {
	// The marketplace the fulfillment order is placed against.
	MarketplaceId string `json:"marketplaceId,omitempty"`
	// A fulfillment order identifier that the seller creates to track their fulfillment order. The `sellerFulfillmentOrderId` must be unique for each fulfillment order that a seller creates. If the seller's system already creates unique order identifiers, then these might be good values for them to use.
	SellerFulfillmentOrderId string `json:"sellerFulfillmentOrderId"`
	// A fulfillment order identifier that the seller creates. This value displays as the order identifier in recipient-facing materials such as the outbound shipment packing slip. The value of `displayableOrderId` should match the order identifier that the seller provides to the recipient. The seller can use the SellerFulfillmentOrderId for this value or they can specify an alternate value if they want the recipient to reference an alternate order identifier.  The value must be an alpha-numeric or ISO 8859-1 compliant string from one to 40 characters in length. Cannot contain two spaces in a row. Leading and trailing white space is removed.
	DisplayableOrderId string `json:"displayableOrderId"`
	DisplayableOrderDate *time.Time `json:"displayableOrderDate"`
	// Order-specific text that appears in recipient-facing materials such as the outbound shipment packing slip.
	DisplayableOrderComment string `json:"displayableOrderComment"`
	ShippingSpeedCategory *ShippingSpeedCategory `json:"shippingSpeedCategory"`
	DeliveryWindow *DeliveryWindow `json:"deliveryWindow,omitempty"`
	DestinationAddress *Address `json:"destinationAddress"`
	DeliveryPreferences *DeliveryPreferences `json:"deliveryPreferences,omitempty"`
	FulfillmentAction *FulfillmentAction `json:"fulfillmentAction,omitempty"`
	FulfillmentPolicy *FulfillmentPolicy `json:"fulfillmentPolicy,omitempty"`
	CodSettings *CodSettings `json:"codSettings,omitempty"`
	// The two-character country code for the country from which the fulfillment order ships. Must be in ISO 3166-1 alpha-2 format.
	ShipFromCountryCode string `json:"shipFromCountryCode,omitempty"`
	NotificationEmails *[]string `json:"notificationEmails,omitempty"`
	// A list of features and their fulfillment policies to apply to the order.
	FeatureConstraints []FeatureSettings `json:"featureConstraints,omitempty"`
	Items *[]CreateFulfillmentOrderItem `json:"items"`
	PaymentInformation *[]PaymentInformation `json:"paymentInformation,omitempty"`
}
