/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01

// An item that Amazon accepted for return.
type CreateReturnItem struct {
	// An identifier the seller assigns to the return item.
	SellerReturnItemId string `json:"sellerReturnItemId"`
	// The identifier assigned to the item by the seller when the fulfillment order was created.
	SellerFulfillmentOrderItemId string `json:"sellerFulfillmentOrderItemId"`
	// The identifier for the shipment that is associated with the return item.
	AmazonShipmentId string `json:"amazonShipmentId"`
	// The return reason code assigned to the return item by the seller.
	ReturnReasonCode string `json:"returnReasonCode"`
	// An optional comment about the return item.
	ReturnComment string `json:"returnComment,omitempty"`
}
