/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fulfillment_outbound_v2020_07_01
// AdditionalLocationInfo : Additional location information.
type AdditionalLocationInfo string

// List of AdditionalLocationInfo
const (
	AS_INSTRUCTED_AdditionalLocationInfo AdditionalLocationInfo = "AS_INSTRUCTED"
	CARPORT_AdditionalLocationInfo AdditionalLocationInfo = "CARPORT"
	CUSTOMER_PICKUP_AdditionalLocationInfo AdditionalLocationInfo = "CUSTOMER_PICKUP"
	DECK_AdditionalLocationInfo AdditionalLocationInfo = "DECK"
	DOOR_PERSON_AdditionalLocationInfo AdditionalLocationInfo = "DOOR_PERSON"
	FRONT_DESK_AdditionalLocationInfo AdditionalLocationInfo = "FRONT_DESK"
	FRONT_DOOR_AdditionalLocationInfo AdditionalLocationInfo = "FRONT_DOOR"
	GARAGE_AdditionalLocationInfo AdditionalLocationInfo = "GARAGE"
	GUARD_AdditionalLocationInfo AdditionalLocationInfo = "GUARD"
	MAIL_ROOM_AdditionalLocationInfo AdditionalLocationInfo = "MAIL_ROOM"
	MAIL_SLOT_AdditionalLocationInfo AdditionalLocationInfo = "MAIL_SLOT"
	MAILBOX_AdditionalLocationInfo AdditionalLocationInfo = "MAILBOX"
	MC_BOY_AdditionalLocationInfo AdditionalLocationInfo = "MC_BOY"
	MC_GIRL_AdditionalLocationInfo AdditionalLocationInfo = "MC_GIRL"
	MC_MAN_AdditionalLocationInfo AdditionalLocationInfo = "MC_MAN"
	MC_WOMAN_AdditionalLocationInfo AdditionalLocationInfo = "MC_WOMAN"
	NEIGHBOR_AdditionalLocationInfo AdditionalLocationInfo = "NEIGHBOR"
	OFFICE_AdditionalLocationInfo AdditionalLocationInfo = "OFFICE"
	OUTBUILDING_AdditionalLocationInfo AdditionalLocationInfo = "OUTBUILDING"
	PATIO_AdditionalLocationInfo AdditionalLocationInfo = "PATIO"
	PORCH_AdditionalLocationInfo AdditionalLocationInfo = "PORCH"
	REAR_DOOR_AdditionalLocationInfo AdditionalLocationInfo = "REAR_DOOR"
	RECEPTIONIST_AdditionalLocationInfo AdditionalLocationInfo = "RECEPTIONIST"
	RECEIVER_AdditionalLocationInfo AdditionalLocationInfo = "RECEIVER"
	SECURE_LOCATION_AdditionalLocationInfo AdditionalLocationInfo = "SECURE_LOCATION"
	SIDE_DOOR_AdditionalLocationInfo AdditionalLocationInfo = "SIDE_DOOR"
)
