/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// An object which contains metric data for a selling partner.
type GetSellingPartnerMetricsResponseMetric struct {
	// The percentage of items that were not shipped out of the total shipped units over a period of time due to being out of stock. Applicable to PERFORMANCE timePeriodType.
	NotDeliveredDueToOOS float64 `json:"notDeliveredDueToOOS,omitempty"`
	// The revenue generated from subscriptions over a period of time. Applicable for both the PERFORMANCE and FORECAST timePeriodType.
	TotalSubscriptionsRevenue float64 `json:"totalSubscriptionsRevenue,omitempty"`
	// The number of units shipped to the subscribers over a period of time. Applicable for both the PERFORMANCE and FORECAST timePeriodType.
	ShippedSubscriptionUnits float64 `json:"shippedSubscriptionUnits,omitempty"`
	// The number of active subscriptions present at the end of the period. Applicable to PERFORMANCE timePeriodType.
	ActiveSubscriptions float64 `json:"activeSubscriptions,omitempty"`
	// The average revenue per subscriber of the program over a period of past 12 months for sellers and 6 months for vendors. Applicable to PERFORMANCE timePeriodType.
	SubscriberAverageRevenue float64 `json:"subscriberAverageRevenue,omitempty"`
	// The average revenue per non-subscriber of the program over a period of past 12 months for sellers and 6 months for vendors. Applicable to PERFORMANCE timePeriodType.
	NonSubscriberAverageRevenue float64 `json:"nonSubscriberAverageRevenue,omitempty"`
	// The revenue that would have been generated had there not been out of stock. Applicable to PERFORMANCE timePeriodType.
	LostRevenueDueToOOS float64 `json:"lostRevenueDueToOOS,omitempty"`
	// The average reorders per subscriber of the program over a period of 12 months. Applicable to PERFORMANCE timePeriodType.
	SubscriberAverageReorders float64 `json:"subscriberAverageReorders,omitempty"`
	// The average reorders per non-subscriber of the program over a period of past 12 months. Applicable to PERFORMANCE timePeriodType.
	NonSubscriberAverageReorders float64 `json:"nonSubscriberAverageReorders,omitempty"`
	// The percentage of revenue from ASINs with coupons out of total revenue from all ASINs. Applicable to PERFORMANCE timePeriodType.
	CouponsRevenuePenetration float64 `json:"couponsRevenuePenetration,omitempty"`
	// The subscription revenue generated from subscriptions with over two deliveries over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromSubscriptionsWithMultipleDeliveries float64 `json:"revenueFromSubscriptionsWithMultipleDeliveries,omitempty"`
	// The subscription revenue generated from active subscriptions with one delivery over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromActiveSubscriptionsWithSingleDelivery float64 `json:"revenueFromActiveSubscriptionsWithSingleDelivery,omitempty"`
	// The subscription revenue generated from subscriptions which are cancelled after one delivery over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromCancelledSubscriptionsAfterSingleDelivery float64 `json:"revenueFromCancelledSubscriptionsAfterSingleDelivery,omitempty"`
	// The percentage of subscriptions retained after 30 days of subscription creation. Applicable to PERFORMANCE timePeriodType.
	SubscriberRetentionFor30Days float64 `json:"subscriberRetentionFor30Days,omitempty"`
	// The percentage of subscriptions retained after 90 days of subscription creation. Applicable to PERFORMANCE timePeriodType.
	SubscriberRetentionFor90Days float64 `json:"subscriberRetentionFor90Days,omitempty"`
	// The percentage of subscription revenue generated by offers with 0% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor0PercentSellerFunding float64 `json:"revenuePenetrationFor0PercentSellerFunding,omitempty"`
	// [Applicable only for Sellers] The percentage of subscription revenue generated by offers with 5% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor5PercentSellerFunding float64 `json:"revenuePenetrationFor5PercentSellerFunding,omitempty"`
	// [Applicable only for Sellers] The percentage of subscription revenue generated by offers with 10% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor10PercentSellerFunding float64 `json:"revenuePenetrationFor10PercentSellerFunding,omitempty"`
	// [Applicable only for vendors] The percentage of subscription revenue generated by offers with 5% or above seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor5PlusPercentSellerFunding float64 `json:"revenuePenetrationFor5PlusPercentSellerFunding,omitempty"`
	// The percentage of new subscriptions acquired through coupons. Applicable to PERFORMANCE timePeriodType.
	ShareOfCouponSubscriptions float64       `json:"shareOfCouponSubscriptions,omitempty"`
	TimeInterval               *TimeInterval `json:"timeInterval,omitempty"`
	// The currency code in ISO 4217 format.
	CurrencyCode string `json:"currencyCode,omitempty"`
}
