/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// A promotional percentage discount applied to the offer.
type OfferProgramConfigurationPromotionsDiscountFunding struct {
	// The percentage discount on the offer.
	Percentage float64 `json:"percentage,omitempty"`
}
