/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07
// ListOffersSortKey : The attribute to use to sort the results.
type ListOffersSortKey string

// List of ListOffersSortKey
const (
	ASIN_ListOffersSortKey ListOffersSortKey = "ASIN"
	SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE_ListOffersSortKey ListOffersSortKey = "SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE"
	SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE_ListOffersSortKey ListOffersSortKey = "SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE"
	AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE_ListOffersSortKey ListOffersSortKey = "AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE"
	AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE_ListOffersSortKey ListOffersSortKey = "AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE"
)
