/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// An object which contains details about an offer.
type ListOffersResponseOffer struct {
	// The SKU. This property is only supported for sellers and not for vendors.
	Sku string `json:"sku,omitempty"`
	// The Amazon Standard Identification Number (ASIN).
	Asin string `json:"asin,omitempty"`
	MarketplaceId string `json:"marketplaceId,omitempty"`
	Eligibility *EligibilityStatus `json:"eligibility,omitempty"`
	OfferProgramConfiguration *OfferProgramConfiguration `json:"offerProgramConfiguration,omitempty"`
	ProgramType *ProgramType `json:"programType,omitempty"`
	// A list of vendor codes associated with the offer.
	VendorCodes []string `json:"vendorCodes,omitempty"`
}
