/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// Use these parameters to paginate through the response.
type ListOffersRequestPagination struct {
	// The maximum number of results to return in the response.
	Limit int64 `json:"limit"`
	// The offset from which to retrieve the number of results specified by the `limit` value. The first result is at offset 0.
	Offset int64 `json:"offset"`
}
