/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// Use these parameters to filter results. Any result must match all provided parameters. For any parameter that is an array, the result must match at least one element in the provided array.
type ListOfferMetricsRequestFilters struct {
	AggregationFrequency *AggregationFrequency `json:"aggregationFrequency,omitempty"`
	TimeInterval         *TimeInterval         `json:"timeInterval"`
	TimePeriodType       *TimePeriodType       `json:"timePeriodType"`
	MarketplaceId        string                `json:"marketplaceId"`
	ProgramTypes         *[]ProgramType        `json:"programTypes"`
	// A list of Amazon Standard Identification Numbers (ASINs).
	Asins []string `json:"asins,omitempty"`
}
