/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * API version: 2022-11-07
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package replenishment_v2022_11_07

// Use these parameters to filter results. Any result must match all of the provided parameters. For any parameter that is an array, the result must match at least one element in the provided array.
type ListOffersRequestFilters struct {
	MarketplaceId string `json:"marketplaceId"`
	// A list of SKUs to filter. This filter is only supported for sellers and not for vendors.
	Skus []string `json:"skus,omitempty"`
	// A list of Amazon Standard Identification Numbers (ASINs).
	Asins []string `json:"asins,omitempty"`
	// A list of eligibilities associated with an offer.
	Eligibilities []EligibilityStatus `json:"eligibilities,omitempty"`
	Preferences   *Preference         `json:"preferences,omitempty"`
	Promotions    *Promotion          `json:"promotions,omitempty"`
	ProgramTypes  *[]ProgramType      `json:"programTypes"`
}
