/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package aplus_content_v2020_11_01

// A reference to an image, hosted in the A+ Content media library.
type ImageComponent struct {
	// This identifier is provided by the [Uploads API](https://developer-docs.amazon.com/sp-api/reference/welcome-to-api-references).
	UploadDestinationId string `json:"uploadDestinationId"`
	ImageCropSpecification *ImageCropSpecification `json:"imageCropSpecification"`
	// The alternative text for the image.
	AltText string `json:"altText"`
}
