/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package aplus_content_v2020_11_01

// An A+ Content module. An A+ Content document is composed of content modules. The `contentModuleType` property selects which content module types to use.
type ContentModule struct {
	ContentModuleType *ContentModuleType `json:"contentModuleType"`
	StandardCompanyLogo *StandardCompanyLogoModule `json:"standardCompanyLogo,omitempty"`
	StandardComparisonTable *StandardComparisonTableModule `json:"standardComparisonTable,omitempty"`
	StandardFourImageText *StandardFourImageTextModule `json:"standardFourImageText,omitempty"`
	StandardFourImageTextQuadrant *StandardFourImageTextQuadrantModule `json:"standardFourImageTextQuadrant,omitempty"`
	StandardHeaderImageText *StandardHeaderImageTextModule `json:"standardHeaderImageText,omitempty"`
	StandardImageSidebar *StandardImageSidebarModule `json:"standardImageSidebar,omitempty"`
	StandardImageTextOverlay *StandardImageTextOverlayModule `json:"standardImageTextOverlay,omitempty"`
	StandardMultipleImageText *StandardMultipleImageTextModule `json:"standardMultipleImageText,omitempty"`
	StandardProductDescription *StandardProductDescriptionModule `json:"standardProductDescription,omitempty"`
	StandardSingleImageHighlights *StandardSingleImageHighlightsModule `json:"standardSingleImageHighlights,omitempty"`
	StandardSingleImageSpecsDetail *StandardSingleImageSpecsDetailModule `json:"standardSingleImageSpecsDetail,omitempty"`
	StandardSingleSideImage *StandardSingleSideImageModule `json:"standardSingleSideImage,omitempty"`
	StandardTechSpecs *StandardTechSpecsModule `json:"standardTechSpecs,omitempty"`
	StandardText *StandardTextModule `json:"standardText,omitempty"`
	StandardThreeImageText *StandardThreeImageTextModule `json:"standardThreeImageText,omitempty"`
}
