/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package aplus_content_v2020_11_01

// A decorator that is applied to a content string value in order to create rich text.
type Decorator struct {
	Type_ *DecoratorType `json:"type,omitempty"`
	// The starting value of this decorator within the content string. Use zero (`0`) for the first value.
	Offset int32 `json:"offset,omitempty"`
	// The number of content characters to alter with this decorator. Decorators, such as line breaks, can have zero length and fit between characters.
	Length int32 `json:"length,omitempty"`
	// The relative intensity or variation of this decorator. Decorators, such as bullet-points, can have multiple indentation depths.
	Depth int32 `json:"depth,omitempty"`
}
