/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package aplus_content_v2020_11_01

// The A+ Content standard comparison product block.
type StandardComparisonProductBlock struct {
	// The rank or index of this comparison product block within the module. Different blocks cannot occupy the same position within a single module.
	Position int32           `json:"position"`
	Image    *ImageComponent `json:"image,omitempty"`
	// The comparison product title.
	Title string `json:"title,omitempty"`
	Asin  string `json:"asin,omitempty"`
	// When true, indicates that this content block is visually highlighted.
	Highlight bool `json:"highlight,omitempty"`
	// Comparison metrics for the product.
	Metrics []PlainTextItem `json:"metrics,omitempty"`
}
