/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package aplus_content_v2020_11_01
// ContentBadge : A flag that provides additional information about an A+ Content document.
type ContentBadge string

// List of ContentBadge
const (
	BULK_ContentBadge ContentBadge = "BULK"
	GENERATED_ContentBadge ContentBadge = "GENERATED"
	LAUNCHPAD_ContentBadge ContentBadge = "LAUNCHPAD"
	PREMIUM_ContentBadge ContentBadge = "PREMIUM"
	STANDARD_ContentBadge ContentBadge = "STANDARD"
)
