/*
 * Selling Partner API for Uploads
 *
 * The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package uploads_v2020_11_01

// The response schema for the createUploadDestination operation.
type CreateUploadDestinationResponse struct {
	Payload *UploadDestination `json:"payload,omitempty"`
	Errors  *[]ModelError      `json:"errors,omitempty"`
}
