/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// The curbside pickup configuration of a supply source.
type CurbsidePickupConfiguration struct {
	// When true, curbside pickup is supported by the supply source.
	IsSupported                     bool                             `json:"isSupported,omitempty"`
	OperationalConfiguration        *OperationalConfiguration        `json:"operationalConfiguration,omitempty"`
	ParkingWithAddressConfiguration *ParkingWithAddressConfiguration `json:"parkingWithAddressConfiguration,omitempty"`
}
