/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01
// SupplySourceStatusReadOnly : The `SupplySource` status.
type SupplySourceStatusReadOnly string

// List of SupplySourceStatusReadOnly
const (
	ACTIVE_SupplySourceStatusReadOnly SupplySourceStatusReadOnly = "Active"
	INACTIVE_SupplySourceStatusReadOnly SupplySourceStatusReadOnly = "Inactive"
	ARCHIVED_SupplySourceStatusReadOnly SupplySourceStatusReadOnly = "Archived"
)
