/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// The outbound capability of a supply source.
type OutboundCapability struct {
	IsSupported              bool                      `json:"isSupported,omitempty"`
	OperationalConfiguration *OperationalConfiguration `json:"operationalConfiguration,omitempty"`
	ReturnLocation           *ReturnLocation           `json:"returnLocation,omitempty"`
	DeliveryChannel          *DeliveryChannel          `json:"deliveryChannel,omitempty"`
	PickupChannel            *PickupChannel            `json:"pickupChannel,omitempty"`
}
