/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

type SupplySourceListInner struct {
	Alias string `json:"alias,omitempty"`
	SupplySourceId string `json:"supplySourceId,omitempty"`
	SupplySourceCode string `json:"supplySourceCode,omitempty"`
	Address *Address `json:"address,omitempty"`
}
