/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01
// TimeUnit : The time unit
type TimeUnit string

// List of TimeUnit
const (
	HOURS_TimeUnit TimeUnit = "Hours"
	MINUTES_TimeUnit TimeUnit = "Minutes"
	DAYS_TimeUnit TimeUnit = "Days"
)
