/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// A list of error responses returned when a request is unsuccessful.
type ErrorList struct {
	// A list of error responses returned when a request is unsuccessful.
	Errors []ModelError `json:"errors"`
}
