/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// A request to create a supply source.
type CreateSupplySourceRequest struct {
	SupplySourceCode string `json:"supplySourceCode"`
	Alias string `json:"alias"`
	Address *Address `json:"address"`
}
