/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// The paginated list of supply sources.
type GetSupplySourcesResponse struct {
	SupplySources *[]SupplySourceListInner `json:"supplySources,omitempty"`
	// If present, use this pagination token to retrieve the next page of supply sources.
	NextPageToken string `json:"nextPageToken,omitempty"`
}
