/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// The operational configuration of `supplySources`.
type OperationalConfiguration struct {
	ContactDetails *ContactDetails `json:"contactDetails,omitempty"`
	ThroughputConfig *ThroughputConfig `json:"throughputConfig,omitempty"`
	OperatingHoursByDay *OperatingHoursByDay `json:"operatingHoursByDay,omitempty"`
	HandlingTime *Duration `json:"handlingTime,omitempty"`
}
