/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

// The duration of time.
type Duration struct {
	Value    int32     `json:"value,omitempty"`
	TimeUnit *TimeUnit `json:"timeUnit,omitempty"`
}
