/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * API version: 2020-07-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package supply_sources_v2020_07_01

type ContactDetailsPrimary struct {
	Email string `json:"email,omitempty"`
	// The phone number of the person, business or institution.
	Phone string `json:"phone,omitempty"`
}
